"use client";

import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'fr' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  dir: 'ltr' | 'rtl';
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // ── Navigation & Layout ─────────────────────────────────────
    dashboard: 'Dashboard',
    aiExtraction: 'AI Extraction',
    invoiceManagement: 'Invoice Management',
    aiAdvisor: 'AI Advisor',
    settings: 'Settings',
    logout: 'Logout',
    auditTrail: 'Audit Trail',
    invoices: 'Invoices',

    // ── Dashboard ───────────────────────────────────────────────
    totalRevenue: 'Total Revenue',
    totalExpenses: 'Total Expenses',
    financialTrends: 'Financial Trends',
    totalAmount: 'Total Amount',
    totalInvoices: 'Total Invoices',
    needsReview: 'Needs Review',
    avgInvoiceValue: 'Avg Invoice Value',
    monthlyInvoiceTrend: 'Monthly Invoice Trend',
    topVendors: 'Top Vendors',
    invoiceStatusBreakdown: 'Invoice Status Breakdown',
    monthlyInvoiceVolume: 'Monthly Invoice Volume',
    recentInvoices: 'Recent Invoices',
    quickStats: 'Quick Stats',
    totalProcessed: 'Total Processed',
    reviewRate: 'Review Rate',
    topVendor: 'Top Vendor',
    noData: 'No data available',

    // ── AI Extraction ───────────────────────────────────────────
    uploadInvoice: 'Upload Invoice',
    dragDrop: 'Drag & drop your PDF or image here',
    extractedData: 'Extracted Data',
    saveInvoice: 'Save Invoice',
    multiFile: 'Multi-file',
    zipSupport: 'ZIP support',
    batchUpload: 'Batch Upload',
    processing: 'Processing',
    completed: 'Completed',
    failed: 'Failed',

    // ── Invoice Management ──────────────────────────────────────
    createInvoice: 'Create Invoice',
    allInvoices: 'All Invoices',
    invoiceNumber: 'Invoice Number',
    supplier: 'Supplier',
    amount: 'Amount',
    date: 'Date',
    status: 'Status',
    actions: 'Actions',
    exportPDF: 'Export PDF',
    exportExcel: 'Export Excel',
    exportAll: 'Export All',
    exportAllExcel: 'Export All (Excel)',
    description: 'Description',
    vat: 'VAT',

    // ── Search & Filters ────────────────────────────────────────
    searchInvoices: 'Search invoices by vendor, invoice number, notes...',
    filters: 'Filters',
    clearAll: 'Clear all',
    allStatuses: 'All statuses',
    allVendors: 'All vendors',
    allCurrencies: 'All currencies',
    sortBy: 'Sort by',
    dateAdded: 'Date added',
    invoiceDate: 'Invoice date',
    vendor: 'Vendor',
    dateFrom: 'Date from',
    dateTo: 'Date to',
    minAmount: 'Min amount',
    maxAmount: 'Max amount',
    currency: 'Currency',
    results: 'results',
    result: 'result',
    page: 'Page',
    of: 'of',
    total: 'Total',
    previous: 'Previous',
    next: 'Next',
    noInvoicesMatch: 'No invoices match your filters',
    tryAdjusting: 'Try adjusting your search or filters',
    clearAllFilters: 'Clear all filters',
    noInvoicesYet: 'No invoices yet. Upload a file in AI Extraction or create one manually.',
    invoice: 'invoice',

    // ── Create Invoice Dialog ───────────────────────────────────
    invoiceDetails: 'Invoice Details',
    invoiceNo: 'Invoice Number',
    invoiceDateLabel: 'Invoice Date',
    dueDate: 'Due Date',
    vendorFrom: 'Vendor (From)',
    vendorName: 'Vendor / Supplier Name',
    billTo: 'Bill To (Customer)',
    name: 'Name',
    email: 'Email',
    address: 'Address',
    lineItems: 'Line Items',
    addItem: 'Add Item',
    qty: 'Qty',
    unitPrice: 'Unit Price',
    totals: 'Totals',
    subtotal: 'Subtotal',
    tax: 'Tax',
    discount: 'Discount',
    grandTotal: 'Grand Total',
    paymentMethod: 'Payment Method',
    notes: 'Notes',
    cancel: 'Cancel',
    creating: 'Creating...',
    manageExport: 'Manage and export your invoices with AI-powered tools',

    // ── AI Advisor ──────────────────────────────────────────────
    askAI: 'Ask AI Advisor...',
    send: 'Send',
    newChat: 'New Chat',
    aiFinancialAdvisor: 'AI Financial Advisor',
    aiAdvisorDesc: 'Ask me anything about your invoices, spending patterns, vendor analysis, or financial insights.',
    realData: 'real data',
    tryAskingAbout: 'Try asking about',
    spendingTrends: 'Spending Trends',
    costOptimization: 'Cost Optimization',
    reviewNeeded: 'Review Needed',
    monthlySummary: 'Monthly Summary',
    financialHealth: 'Financial Health',
    realTimeAnalysis: 'Real-time analysis',
    multiTurnChat: 'Multi-turn chat',
    yourDataOnly: 'Your data only',
    analyzingData: 'Analyzing your data...',
    poweredByAI: 'Powered by AI — Analyzes your real invoice data',
    aiResponseNote: 'AI analyzes your real invoice data. Responses may take a moment.',

    // ── Audit Trail ─────────────────────────────────────────────
    actionType: 'Action type',
    allActions: 'All actions',
    user: 'User',
    details: 'Details',
    ipAddress: 'IP Address',
    timestamp: 'Timestamp',
    login: 'Login',
    registration: 'Registration',
    invoiceUpload: 'Invoice Upload',
    invoiceUpdate: 'Invoice Update',
    export: 'Export',
    invoiceView: 'Invoice View',
    invoiceDelete: 'Invoice Delete',
    profileUpdate: 'Profile Update',
    aiAdvisorChat: 'AI Advisor Chat',

    // ── Auth ────────────────────────────────────────────────────
    admin: 'Admin',
    client: 'Client',
    month: 'Month',
    revenue: 'Revenue',
    expenses: 'Expenses',

    // ── Theme ───────────────────────────────────────────────────
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    systemTheme: 'System',
    language: 'Language',
    english: 'English',
    french: 'French',
    arabic: 'Arabic',

    // ── User Management ────────────────────────────────────────
    userManagement: 'User Management',
    userManagementDesc: 'Manage all users, roles and permissions',
    users: 'Users',
    addUser: 'Add User',
    editUser: 'Edit User',
    createUser: 'Create User',
    saveChanges: 'Save Changes',
    deleteUser: 'Delete User',
    deleteUserTitle: 'Delete User',
    deleteUserConfirm: 'Are you sure you want to permanently delete',
    deleteUserWarning: 'This action cannot be undone.',
    delete: 'Delete',
    activateUser: 'Activate User',
    deactivateUser: 'Deactivate User',
    active: 'Active',
    inactive: 'Inactive',
    role: 'Role',
    allRoles: 'All roles',
    password: 'Password',
    newPassword: 'New Password',
    leaveBlankPassword: 'Leave blank to keep current',
    searchUsers: 'Search Users',
    searchByNameEmail: 'Search by name or email...',
    noUsersFound: 'No users found',
    noUsersYet: 'No users have been created yet',
    createdAt: 'Created',
    lastLogin: 'Last Login',

    // ── Notifications ──────────────────────────────────────────
    notifications: 'Notifications',
    notificationCenter: 'Notification Center',
    notificationPreferences: 'Notification Preferences',
    markAllRead: 'Mark all as read',
    viewAll: 'View All',
    noNotifications: 'No notifications',
    noNotificationsYet: 'You have no notifications yet',
    allNotifications: 'All Notifications',
    unread: 'Unread',
    read: 'Read',
    allCategories: 'All categories',
    extraction: 'Extraction',
    invoiceActivity: 'Invoice Activity',
    system: 'System',
    broadcast: 'Broadcast',
    deleteNotification: 'Delete Notification',
    preferences: 'Preferences',
    channels: 'Channels',
    inApp: 'In-App',
    sms: 'SMS',
    notificationTypes: 'Notification Types',
    quietHours: 'Quiet Hours',
    quietHoursDesc: 'Pause non-urgent notifications during specified hours',
    startTime: 'Start Time',
    endTime: 'End Time',
    dailyDigest: 'Daily Digest',
    dailyDigestDesc: 'Receive a summary of notifications instead of individual alerts',
    digestFrequency: 'Frequency',
    digestTime: 'Delivery Time',
    daily: 'Daily',
    weekly: 'Weekly',
    saving: 'Saving...',
    saved: 'Saved',
    save: 'Save',

    // ── Organization / SaaS ────────────────────────────────────
    team: 'Team',
    teamManagement: 'Team Management',
    teamManagementDesc: 'Manage your organization members and invitations',
    inviteMember: 'Invite Member',
    sendInvitation: 'Send Invitation',
    invitationSent: 'Invitation sent to',
    pendingInvitations: 'Pending Invitations',
    revoke: 'Revoke',
    revokeInvitation: 'Revoke Invitation',
    revokeInvitationConfirm: 'Revoke the invitation sent to',
    removeMember: 'Remove Member',
    removeMemberConfirm: 'Are you sure you want to remove',
    remove: 'Remove',
    roleUpdated: 'Role updated',
    memberRemoved: 'Member removed',
    invitationRevoked: 'Invitation revoked',
    members: 'Members',
    owner: 'Owner',
    member: 'Member',
    you: 'you',
    orgSettings: 'Settings',
    orgSettingsDesc: 'Manage your organization settings',
    orgName: 'Organization Name',
    orgNamePlaceholder: 'e.g. Acme Corp',
    createOrganization: 'Create Organization',
    switchedToOrg: 'Switched organization',
    switchOrgFailed: 'Failed to switch organization',
    createOrgFailed: 'Failed to create organization',
    general: 'General',
    orgGeneralDesc: 'Basic organization settings',
    defaultCurrency: 'Default Currency',
    timezone: 'Timezone',
    branding: 'Branding',
    brandingDesc: 'Customize your organization appearance',
    primaryColor: 'Primary Color',
    billing: 'Billing',
    currentPlan: 'Current Plan',
    manageBilling: 'Manage Billing',
    invoicesThisMonth: 'Invoices this month',
    teamMembers: 'Team members',
    aiQueries: 'AI queries this month',
    storage: 'Storage (MB)',
    upgradeToPro: 'Upgrade to Pro',
    upgradeToEnterprise: 'Upgrade to Enterprise',
    billingUnavailable: 'Billing information unavailable',
    dangerZone: 'Danger Zone',
    deactivateOrg: 'Deactivate Organization',
    deleteOrgWarning: 'Deactivating the organization will remove access for all members.',
    deactivateOrgConfirm: 'This will deactivate the organization. This can be reversed by contacting support.',
    deactivate: 'Deactivate',

    // ── Tunisia 2026 E-Invoicing Compliance ────────────────────────────
    compliance: 'Compliance',
    tunisiaCompliance: 'Tunisia 2026 Compliance',
    complianceScore: 'Compliance Score',
    compliant: 'Compliant',
    nonCompliant: 'Non-compliant',
    pendingReview: 'Pending',
    runValidation: 'Validate',
    loadReport: 'Load Report',
    refresh: 'Refresh',
    errors: 'Errors',
    warnings: 'Warnings',
    suggestions: 'Suggestions',
    checksPassed: 'checks passed',
    sellerVatId: 'Seller VAT ID',
    buyerVatId: 'Buyer VAT ID',
    digitalSignature: 'Digital Signature',
    verify: 'Verify',
    noSignature: 'No signature',
    notVerified: 'Not verified yet',
    ttnSubmission: 'TTN El Fatoora',
    submitToTTN: 'Submit',
    submitted: 'Submitted',
    submittedOn: 'Submitted on',
    notSubmitted: 'Not submitted yet',
    mustBeCompliant: 'Invoice must be compliant first',
    invoiceCompliant: 'Invoice is compliant',
    invoiceNonCompliant: 'Invoice has compliance issues',
    validationFailed: 'Validation failed',
    complianceLoadFailed: 'Failed to load compliance report',
    signatureVerified: 'Signature verified',
    noSignatureFound: 'No digital signature found',
    ttnSubmitted: 'Submitted to TTN',
    xmlFormat: 'XML Format',
    goods: 'Goods',
    services: 'Services',
    mixed: 'Mixed',

    // ── Camera Capture ──────────────────────────────────────────
    scanInvoice: 'Scan Invoice',
    takePhoto: 'Take Photo',
    switchCamera: 'Switch Camera',
    cameraAccessDenied: 'Camera access denied. Please allow camera permissions.',
    captureInvoice: 'Position the invoice in frame and tap capture',
  },

  fr: {
    // ── Navigation & Layout ─────────────────────────────────────
    dashboard: 'Tableau de bord',
    aiExtraction: 'Extraction IA',
    invoiceManagement: 'Gestion des factures',
    aiAdvisor: 'Conseiller IA',
    settings: 'Paramètres',
    logout: 'Déconnexion',
    auditTrail: 'Journal d\'audit',
    invoices: 'Factures',

    // ── Dashboard ───────────────────────────────────────────────
    totalRevenue: 'Revenu total',
    totalExpenses: 'Dépenses totales',
    financialTrends: 'Tendances financières',
    totalAmount: 'Montant total',
    totalInvoices: 'Total factures',
    needsReview: 'À vérifier',
    avgInvoiceValue: 'Valeur moyenne',
    monthlyInvoiceTrend: 'Tendance mensuelle des factures',
    topVendors: 'Top fournisseurs',
    invoiceStatusBreakdown: 'Répartition par statut',
    monthlyInvoiceVolume: 'Volume mensuel des factures',
    recentInvoices: 'Factures récentes',
    quickStats: 'Statistiques rapides',
    totalProcessed: 'Total traité',
    reviewRate: 'Taux de vérification',
    topVendor: 'Fournisseur principal',
    noData: 'Aucune donnée disponible',

    // ── AI Extraction ───────────────────────────────────────────
    uploadInvoice: 'Télécharger la facture',
    dragDrop: 'Glissez-déposez votre PDF ou image ici',
    extractedData: 'Données extraites',
    saveInvoice: 'Enregistrer la facture',
    multiFile: 'Multi-fichier',
    zipSupport: 'Support ZIP',
    batchUpload: 'Téléchargement par lot',
    processing: 'En cours',
    completed: 'Terminé',
    failed: 'Échoué',

    // ── Invoice Management ──────────────────────────────────────
    createInvoice: 'Créer une facture',
    allInvoices: 'Toutes les factures',
    invoiceNumber: 'Numéro de facture',
    supplier: 'Fournisseur',
    amount: 'Montant',
    date: 'Date',
    status: 'Statut',
    actions: 'Actions',
    exportPDF: 'Exporter PDF',
    exportExcel: 'Exporter Excel',
    exportAll: 'Tout exporter',
    exportAllExcel: 'Tout exporter (Excel)',
    description: 'Description',
    vat: 'TVA',

    // ── Search & Filters ────────────────────────────────────────
    searchInvoices: 'Rechercher par fournisseur, numéro, notes...',
    filters: 'Filtres',
    clearAll: 'Tout effacer',
    allStatuses: 'Tous les statuts',
    allVendors: 'Tous les fournisseurs',
    allCurrencies: 'Toutes les devises',
    sortBy: 'Trier par',
    dateAdded: 'Date d\'ajout',
    invoiceDate: 'Date de facture',
    vendor: 'Fournisseur',
    dateFrom: 'Date début',
    dateTo: 'Date fin',
    minAmount: 'Montant min',
    maxAmount: 'Montant max',
    currency: 'Devise',
    results: 'résultats',
    result: 'résultat',
    page: 'Page',
    of: 'de',
    total: 'Total',
    previous: 'Précédent',
    next: 'Suivant',
    noInvoicesMatch: 'Aucune facture ne correspond à vos filtres',
    tryAdjusting: 'Essayez d\'ajuster votre recherche ou vos filtres',
    clearAllFilters: 'Effacer tous les filtres',
    noInvoicesYet: 'Pas encore de factures. Téléchargez un fichier ou créez-en une manuellement.',
    invoice: 'facture',

    // ── Create Invoice Dialog ───────────────────────────────────
    invoiceDetails: 'Détails de la facture',
    invoiceNo: 'Numéro de facture',
    invoiceDateLabel: 'Date de facture',
    dueDate: 'Date d\'échéance',
    vendorFrom: 'Fournisseur (De)',
    vendorName: 'Nom du fournisseur',
    billTo: 'Facturer à (Client)',
    name: 'Nom',
    email: 'E-mail',
    address: 'Adresse',
    lineItems: 'Articles',
    addItem: 'Ajouter un article',
    qty: 'Qté',
    unitPrice: 'Prix unitaire',
    totals: 'Totaux',
    subtotal: 'Sous-total',
    tax: 'Taxe',
    discount: 'Remise',
    grandTotal: 'Total général',
    paymentMethod: 'Mode de paiement',
    notes: 'Notes',
    cancel: 'Annuler',
    creating: 'Création...',
    manageExport: 'Gérez et exportez vos factures avec des outils alimentés par l\'IA',

    // ── AI Advisor ──────────────────────────────────────────────
    askAI: 'Demander au conseiller IA...',
    send: 'Envoyer',
    newChat: 'Nouvelle discussion',
    aiFinancialAdvisor: 'Conseiller financier IA',
    aiAdvisorDesc: 'Posez-moi des questions sur vos factures, vos dépenses, vos fournisseurs ou vos analyses financières.',
    realData: 'données réelles',
    tryAskingAbout: 'Essayez de demander',
    spendingTrends: 'Tendances de dépenses',
    costOptimization: 'Optimisation des coûts',
    reviewNeeded: 'Vérification requise',
    monthlySummary: 'Résumé mensuel',
    financialHealth: 'Santé financière',
    realTimeAnalysis: 'Analyse en temps réel',
    multiTurnChat: 'Discussion continue',
    yourDataOnly: 'Vos données uniquement',
    analyzingData: 'Analyse de vos données...',
    poweredByAI: 'Propulsé par l\'IA — Analyse vos vraies données de factures',
    aiResponseNote: 'L\'IA analyse vos vraies données de factures. Les réponses peuvent prendre un moment.',

    // ── Audit Trail ─────────────────────────────────────────────
    actionType: 'Type d\'action',
    allActions: 'Toutes les actions',
    user: 'Utilisateur',
    details: 'Détails',
    ipAddress: 'Adresse IP',
    timestamp: 'Horodatage',
    login: 'Connexion',
    registration: 'Inscription',
    invoiceUpload: 'Téléchargement de facture',
    invoiceUpdate: 'Mise à jour de facture',
    export: 'Exportation',
    invoiceView: 'Consultation de facture',
    invoiceDelete: 'Suppression de facture',
    profileUpdate: 'Mise à jour du profil',
    aiAdvisorChat: 'Discussion IA',

    // ── Auth ────────────────────────────────────────────────────
    admin: 'Admin',
    client: 'Client',
    month: 'Mois',
    revenue: 'Revenu',
    expenses: 'Dépenses',

    // ── Theme ───────────────────────────────────────────────────
    darkMode: 'Mode sombre',
    lightMode: 'Mode clair',
    systemTheme: 'Système',
    language: 'Langue',
    english: 'Anglais',
    french: 'Français',
    arabic: 'Arabe',

    // ── User Management ────────────────────────────────────────
    userManagement: 'Gestion des utilisateurs',
    userManagementDesc: 'Gérer tous les utilisateurs, rôles et permissions',
    users: 'Utilisateurs',
    addUser: 'Ajouter un utilisateur',
    editUser: 'Modifier l\'utilisateur',
    createUser: 'Créer l\'utilisateur',
    saveChanges: 'Enregistrer',
    deleteUser: 'Supprimer l\'utilisateur',
    deleteUserTitle: 'Supprimer l\'utilisateur',
    deleteUserConfirm: 'Êtes-vous sûr de vouloir supprimer définitivement',
    deleteUserWarning: 'Cette action est irréversible.',
    delete: 'Supprimer',
    activateUser: 'Activer l\'utilisateur',
    deactivateUser: 'Désactiver l\'utilisateur',
    active: 'Actif',
    inactive: 'Inactif',
    role: 'Rôle',
    allRoles: 'Tous les rôles',
    password: 'Mot de passe',
    newPassword: 'Nouveau mot de passe',
    leaveBlankPassword: 'Laisser vide pour conserver l\'actuel',
    searchUsers: 'Rechercher des utilisateurs',
    searchByNameEmail: 'Rechercher par nom ou email...',
    noUsersFound: 'Aucun utilisateur trouvé',
    noUsersYet: 'Aucun utilisateur n\'a encore été créé',
    createdAt: 'Créé le',
    lastLogin: 'Dernière connexion',

    // ── Notifications ──────────────────────────────────────────
    notifications: 'Notifications',
    notificationCenter: 'Centre de notifications',
    notificationPreferences: 'Préférences de notification',
    markAllRead: 'Tout marquer comme lu',
    viewAll: 'Voir tout',
    noNotifications: 'Aucune notification',
    noNotificationsYet: 'Vous n\'avez pas encore de notifications',
    allNotifications: 'Toutes les notifications',
    unread: 'Non lu',
    read: 'Lu',
    allCategories: 'Toutes les catégories',
    extraction: 'Extraction',
    invoiceActivity: 'Activité de facture',
    system: 'Système',
    broadcast: 'Diffusion',
    deleteNotification: 'Supprimer la notification',
    preferences: 'Préférences',
    channels: 'Canaux',
    inApp: 'Dans l\'app',
    sms: 'SMS',
    notificationTypes: 'Types de notification',
    quietHours: 'Heures calmes',
    quietHoursDesc: 'Suspendre les notifications non urgentes pendant les heures spécifiées',
    startTime: 'Heure de début',
    endTime: 'Heure de fin',
    dailyDigest: 'Résumé quotidien',
    dailyDigestDesc: 'Recevoir un résumé des notifications au lieu d\'alertes individuelles',
    digestFrequency: 'Fréquence',
    digestTime: 'Heure de livraison',
    daily: 'Quotidien',
    weekly: 'Hebdomadaire',
    saving: 'Enregistrement...',
    saved: 'Enregistré',
    save: 'Enregistrer',

    // ── Organization / SaaS ────────────────────────────────────
    team: 'Équipe',
    teamManagement: 'Gestion d\'équipe',
    teamManagementDesc: 'Gérer les membres et les invitations de votre organisation',
    inviteMember: 'Inviter un membre',
    sendInvitation: 'Envoyer l\'invitation',
    invitationSent: 'Invitation envoyée à',
    pendingInvitations: 'Invitations en attente',
    revoke: 'Révoquer',
    revokeInvitation: 'Révoquer l\'invitation',
    revokeInvitationConfirm: 'Révoquer l\'invitation envoyée à',
    removeMember: 'Retirer le membre',
    removeMemberConfirm: 'Êtes-vous sûr de vouloir retirer',
    remove: 'Retirer',
    roleUpdated: 'Rôle mis à jour',
    memberRemoved: 'Membre retiré',
    invitationRevoked: 'Invitation révoquée',
    members: 'Membres',
    owner: 'Propriétaire',
    member: 'Membre',
    you: 'vous',
    orgSettings: 'Paramètres',
    orgSettingsDesc: 'Gérer les paramètres de votre organisation',
    orgName: 'Nom de l\'organisation',
    orgNamePlaceholder: 'ex. Acme Corp',
    createOrganization: 'Créer une organisation',
    switchedToOrg: 'Organisation changée',
    switchOrgFailed: 'Échec du changement d\'organisation',
    createOrgFailed: 'Échec de la création de l\'organisation',
    general: 'Général',
    orgGeneralDesc: 'Paramètres de base de l\'organisation',
    defaultCurrency: 'Devise par défaut',
    timezone: 'Fuseau horaire',
    branding: 'Image de marque',
    brandingDesc: 'Personnaliser l\'apparence de votre organisation',
    primaryColor: 'Couleur principale',
    billing: 'Facturation',
    currentPlan: 'Plan actuel',
    manageBilling: 'Gérer la facturation',
    invoicesThisMonth: 'Factures ce mois-ci',
    teamMembers: 'Membres de l\'équipe',
    aiQueries: 'Requêtes IA ce mois-ci',
    storage: 'Stockage (Mo)',
    upgradeToPro: 'Passer au Pro',
    upgradeToEnterprise: 'Passer à l\'Enterprise',
    billingUnavailable: 'Informations de facturation indisponibles',
    dangerZone: 'Zone de danger',
    deactivateOrg: 'Désactiver l\'organisation',
    deleteOrgWarning: 'La désactivation supprimera l\'accès pour tous les membres.',
    deactivateOrgConfirm: 'Cela désactivera l\'organisation. Cela peut être annulé en contactant le support.',
    deactivate: 'Désactiver',

    // ── Tunisia 2026 E-Invoicing Compliance ────────────────────────────
    compliance: 'Conformité',
    tunisiaCompliance: 'Conformité Tunisie 2026',
    complianceScore: 'Score de conformité',
    compliant: 'Conforme',
    nonCompliant: 'Non conforme',
    pendingReview: 'En attente',
    runValidation: 'Valider',
    loadReport: 'Charger le rapport',
    refresh: 'Actualiser',
    errors: 'Erreurs',
    warnings: 'Avertissements',
    suggestions: 'Suggestions',
    checksPassed: 'vérifications réussies',
    sellerVatId: 'Matricule fiscale vendeur',
    buyerVatId: 'Matricule fiscale acheteur',
    digitalSignature: 'Signature numérique',
    verify: 'Vérifier',
    noSignature: 'Pas de signature',
    notVerified: 'Pas encore vérifié',
    ttnSubmission: 'TTN El Fatoora',
    submitToTTN: 'Soumettre',
    submitted: 'Soumis',
    submittedOn: 'Soumis le',
    notSubmitted: 'Pas encore soumis',
    mustBeCompliant: 'La facture doit être conforme',
    invoiceCompliant: 'La facture est conforme',
    invoiceNonCompliant: 'La facture a des problèmes de conformité',
    validationFailed: 'Échec de la validation',
    complianceLoadFailed: 'Échec du chargement du rapport',
    signatureVerified: 'Signature vérifiée',
    noSignatureFound: 'Aucune signature numérique trouvée',
    ttnSubmitted: 'Soumis au TTN',
    xmlFormat: 'Format XML',
    goods: 'Biens',
    services: 'Services',
    mixed: 'Mixte',

    // ── Camera Capture ──────────────────────────────────────────
    scanInvoice: 'Scanner la facture',
    takePhoto: 'Prendre une photo',
    switchCamera: 'Changer de caméra',
    cameraAccessDenied: "Accès à la caméra refusé. Veuillez autoriser l'accès.",
    captureInvoice: 'Positionnez la facture dans le cadre et appuyez sur capturer',
  },

  ar: {
    // ── Navigation & Layout ─────────────────────────────────────
    dashboard: 'لوحة التحكم',
    aiExtraction: 'استخراج بالذكاء الاصطناعي',
    invoiceManagement: 'إدارة الفواتير',
    aiAdvisor: 'مستشار الذكاء الاصطناعي',
    settings: 'الإعدادات',
    logout: 'تسجيل الخروج',
    auditTrail: 'سجل التدقيق',
    invoices: 'الفواتير',

    // ── Dashboard ───────────────────────────────────────────────
    totalRevenue: 'إجمالي الإيرادات',
    totalExpenses: 'إجمالي المصروفات',
    financialTrends: 'الاتجاهات المالية',
    totalAmount: 'المبلغ الإجمالي',
    totalInvoices: 'إجمالي الفواتير',
    needsReview: 'تحتاج مراجعة',
    avgInvoiceValue: 'متوسط قيمة الفاتورة',
    monthlyInvoiceTrend: 'اتجاه الفواتير الشهرية',
    topVendors: 'أهم الموردين',
    invoiceStatusBreakdown: 'توزيع حالات الفواتير',
    monthlyInvoiceVolume: 'حجم الفواتير الشهرية',
    recentInvoices: 'الفواتير الأخيرة',
    quickStats: 'إحصائيات سريعة',
    totalProcessed: 'إجمالي المعالج',
    reviewRate: 'معدل المراجعة',
    topVendor: 'المورد الرئيسي',
    noData: 'لا توجد بيانات',

    // ── AI Extraction ───────────────────────────────────────────
    uploadInvoice: 'تحميل فاتورة',
    dragDrop: 'اسحب وأفلت ملف PDF أو صورة هنا',
    extractedData: 'البيانات المستخرجة',
    saveInvoice: 'حفظ الفاتورة',
    multiFile: 'ملفات متعددة',
    zipSupport: 'دعم ZIP',
    batchUpload: 'تحميل دفعة',
    processing: 'قيد المعالجة',
    completed: 'مكتمل',
    failed: 'فشل',

    // ── Invoice Management ──────────────────────────────────────
    createInvoice: 'إنشاء فاتورة',
    allInvoices: 'جميع الفواتير',
    invoiceNumber: 'رقم الفاتورة',
    supplier: 'المورد',
    amount: 'المبلغ',
    date: 'التاريخ',
    status: 'الحالة',
    actions: 'الإجراءات',
    exportPDF: 'تصدير PDF',
    exportExcel: 'تصدير Excel',
    exportAll: 'تصدير الكل',
    exportAllExcel: 'تصدير الكل (Excel)',
    description: 'الوصف',
    vat: 'ضريبة القيمة المضافة',

    // ── Search & Filters ────────────────────────────────────────
    searchInvoices: 'البحث عن الفواتير بالمورد أو الرقم أو الملاحظات...',
    filters: 'الفلاتر',
    clearAll: 'مسح الكل',
    allStatuses: 'جميع الحالات',
    allVendors: 'جميع الموردين',
    allCurrencies: 'جميع العملات',
    sortBy: 'ترتيب حسب',
    dateAdded: 'تاريخ الإضافة',
    invoiceDate: 'تاريخ الفاتورة',
    vendor: 'المورد',
    dateFrom: 'من تاريخ',
    dateTo: 'إلى تاريخ',
    minAmount: 'الحد الأدنى',
    maxAmount: 'الحد الأقصى',
    currency: 'العملة',
    results: 'نتائج',
    result: 'نتيجة',
    page: 'صفحة',
    of: 'من',
    total: 'المجموع',
    previous: 'السابق',
    next: 'التالي',
    noInvoicesMatch: 'لا توجد فواتير تطابق الفلاتر',
    tryAdjusting: 'حاول تعديل البحث أو الفلاتر',
    clearAllFilters: 'مسح جميع الفلاتر',
    noInvoicesYet: 'لا توجد فواتير بعد. قم بتحميل ملف أو إنشاء فاتورة يدوياً.',
    invoice: 'فاتورة',

    // ── Create Invoice Dialog ───────────────────────────────────
    invoiceDetails: 'تفاصيل الفاتورة',
    invoiceNo: 'رقم الفاتورة',
    invoiceDateLabel: 'تاريخ الفاتورة',
    dueDate: 'تاريخ الاستحقاق',
    vendorFrom: 'المورد (من)',
    vendorName: 'اسم المورد',
    billTo: 'الفاتورة إلى (العميل)',
    name: 'الاسم',
    email: 'البريد الإلكتروني',
    address: 'العنوان',
    lineItems: 'البنود',
    addItem: 'إضافة بند',
    qty: 'الكمية',
    unitPrice: 'سعر الوحدة',
    totals: 'المجاميع',
    subtotal: 'المجموع الفرعي',
    tax: 'الضريبة',
    discount: 'الخصم',
    grandTotal: 'المجموع الكلي',
    paymentMethod: 'طريقة الدفع',
    notes: 'ملاحظات',
    cancel: 'إلغاء',
    creating: 'جاري الإنشاء...',
    manageExport: 'إدارة وتصدير الفواتير باستخدام أدوات الذكاء الاصطناعي',

    // ── AI Advisor ──────────────────────────────────────────────
    askAI: 'اسأل مستشار الذكاء الاصطناعي...',
    send: 'إرسال',
    newChat: 'محادثة جديدة',
    aiFinancialAdvisor: 'مستشار مالي بالذكاء الاصطناعي',
    aiAdvisorDesc: 'اسألني عن فواتيرك وأنماط الإنفاق وتحليل الموردين أو الرؤى المالية.',
    realData: 'بيانات حقيقية',
    tryAskingAbout: 'جرب أن تسأل عن',
    spendingTrends: 'اتجاهات الإنفاق',
    costOptimization: 'تحسين التكاليف',
    reviewNeeded: 'تحتاج مراجعة',
    monthlySummary: 'ملخص شهري',
    financialHealth: 'الصحة المالية',
    realTimeAnalysis: 'تحليل فوري',
    multiTurnChat: 'محادثة متعددة',
    yourDataOnly: 'بياناتك فقط',
    analyzingData: 'جاري تحليل بياناتك...',
    poweredByAI: 'مدعوم بالذكاء الاصطناعي — يحلل بيانات فواتيرك الحقيقية',
    aiResponseNote: 'يحلل الذكاء الاصطناعي بيانات فواتيرك الحقيقية. قد تستغرق الردود بعض الوقت.',

    // ── Audit Trail ─────────────────────────────────────────────
    actionType: 'نوع الإجراء',
    allActions: 'جميع الإجراءات',
    user: 'المستخدم',
    details: 'التفاصيل',
    ipAddress: 'عنوان IP',
    timestamp: 'الطابع الزمني',
    login: 'تسجيل الدخول',
    registration: 'التسجيل',
    invoiceUpload: 'تحميل فاتورة',
    invoiceUpdate: 'تحديث فاتورة',
    export: 'تصدير',
    invoiceView: 'عرض فاتورة',
    invoiceDelete: 'حذف فاتورة',
    profileUpdate: 'تحديث الملف الشخصي',
    aiAdvisorChat: 'محادثة المستشار',

    // ── Auth ────────────────────────────────────────────────────
    admin: 'مسؤول',
    client: 'عميل',
    month: 'الشهر',
    revenue: 'الإيرادات',
    expenses: 'المصروفات',

    // ── Theme ───────────────────────────────────────────────────
    darkMode: 'الوضع الداكن',
    lightMode: 'الوضع الفاتح',
    systemTheme: 'النظام',
    language: 'اللغة',
    english: 'الإنجليزية',
    french: 'الفرنسية',
    arabic: 'العربية',

    // ── User Management ────────────────────────────────────────
    userManagement: 'إدارة المستخدمين',
    userManagementDesc: 'إدارة جميع المستخدمين والأدوار والصلاحيات',
    users: 'المستخدمون',
    addUser: 'إضافة مستخدم',
    editUser: 'تعديل المستخدم',
    createUser: 'إنشاء المستخدم',
    saveChanges: 'حفظ التغييرات',
    deleteUser: 'حذف المستخدم',
    deleteUserTitle: 'حذف المستخدم',
    deleteUserConfirm: 'هل أنت متأكد من حذف',
    deleteUserWarning: 'لا يمكن التراجع عن هذا الإجراء.',
    delete: 'حذف',
    activateUser: 'تفعيل المستخدم',
    deactivateUser: 'تعطيل المستخدم',
    active: 'نشط',
    inactive: 'غير نشط',
    role: 'الدور',
    allRoles: 'جميع الأدوار',
    password: 'كلمة المرور',
    newPassword: 'كلمة مرور جديدة',
    leaveBlankPassword: 'اتركه فارغاً للإبقاء على الحالي',
    searchUsers: 'البحث عن المستخدمين',
    searchByNameEmail: 'البحث بالاسم أو البريد الإلكتروني...',
    noUsersFound: 'لم يتم العثور على مستخدمين',
    noUsersYet: 'لم يتم إنشاء أي مستخدمين بعد',
    createdAt: 'تاريخ الإنشاء',
    lastLogin: 'آخر تسجيل دخول',

    // ── Notifications ──────────────────────────────────────────
    notifications: 'الإشعارات',
    notificationCenter: 'مركز الإشعارات',
    notificationPreferences: 'تفضيلات الإشعارات',
    markAllRead: 'تحديد الكل كمقروء',
    viewAll: 'عرض الكل',
    noNotifications: 'لا توجد إشعارات',
    noNotificationsYet: 'ليس لديك إشعارات بعد',
    allNotifications: 'جميع الإشعارات',
    unread: 'غير مقروء',
    read: 'مقروء',
    allCategories: 'جميع الفئات',
    extraction: 'الاستخراج',
    invoiceActivity: 'نشاط الفاتورة',
    system: 'النظام',
    broadcast: 'بث عام',
    deleteNotification: 'حذف الإشعار',
    preferences: 'التفضيلات',
    channels: 'القنوات',
    inApp: 'داخل التطبيق',
    sms: 'رسالة نصية',
    notificationTypes: 'أنواع الإشعارات',
    quietHours: 'ساعات الهدوء',
    quietHoursDesc: 'إيقاف الإشعارات غير العاجلة خلال الساعات المحددة',
    startTime: 'وقت البدء',
    endTime: 'وقت الانتهاء',
    dailyDigest: 'ملخص يومي',
    dailyDigestDesc: 'استلام ملخص للإشعارات بدلاً من التنبيهات الفردية',
    digestFrequency: 'التكرار',
    digestTime: 'وقت التسليم',
    daily: 'يومي',
    weekly: 'أسبوعي',
    saving: 'جاري الحفظ...',
    saved: 'تم الحفظ',
    save: 'حفظ',

    // ── Organization / SaaS ────────────────────────────────────
    team: 'الفريق',
    teamManagement: 'إدارة الفريق',
    teamManagementDesc: 'إدارة أعضاء المنظمة والدعوات',
    inviteMember: 'دعوة عضو',
    sendInvitation: 'إرسال الدعوة',
    invitationSent: 'تم إرسال الدعوة إلى',
    pendingInvitations: 'الدعوات المعلقة',
    revoke: 'إلغاء',
    revokeInvitation: 'إلغاء الدعوة',
    revokeInvitationConfirm: 'إلغاء الدعوة المرسلة إلى',
    removeMember: 'إزالة العضو',
    removeMemberConfirm: 'هل أنت متأكد من إزالة',
    remove: 'إزالة',
    roleUpdated: 'تم تحديث الدور',
    memberRemoved: 'تم إزالة العضو',
    invitationRevoked: 'تم إلغاء الدعوة',
    members: 'الأعضاء',
    owner: 'المالك',
    member: 'عضو',
    you: 'أنت',
    orgSettings: 'الإعدادات',
    orgSettingsDesc: 'إدارة إعدادات المنظمة',
    orgName: 'اسم المنظمة',
    orgNamePlaceholder: 'مثال: شركة أكمي',
    createOrganization: 'إنشاء منظمة',
    switchedToOrg: 'تم تغيير المنظمة',
    switchOrgFailed: 'فشل تغيير المنظمة',
    createOrgFailed: 'فشل إنشاء المنظمة',
    general: 'عام',
    orgGeneralDesc: 'الإعدادات الأساسية للمنظمة',
    defaultCurrency: 'العملة الافتراضية',
    timezone: 'المنطقة الزمنية',
    branding: 'العلامة التجارية',
    brandingDesc: 'تخصيص مظهر المنظمة',
    primaryColor: 'اللون الرئيسي',
    billing: 'الفوترة',
    currentPlan: 'الخطة الحالية',
    manageBilling: 'إدارة الفوترة',
    invoicesThisMonth: 'الفواتير هذا الشهر',
    teamMembers: 'أعضاء الفريق',
    aiQueries: 'استعلامات الذكاء الاصطناعي هذا الشهر',
    storage: 'التخزين (ميجابايت)',
    upgradeToPro: 'الترقية إلى Pro',
    upgradeToEnterprise: 'الترقية إلى Enterprise',
    billingUnavailable: 'معلومات الفوترة غير متوفرة',
    dangerZone: 'منطقة الخطر',
    deactivateOrg: 'تعطيل المنظمة',
    deleteOrgWarning: 'سيؤدي التعطيل إلى إزالة الوصول لجميع الأعضاء.',
    deactivateOrgConfirm: 'سيؤدي هذا إلى تعطيل المنظمة. يمكن التراجع عن ذلك بالتواصل مع الدعم.',
    deactivate: 'تعطيل',

    // ── Tunisia 2026 E-Invoicing Compliance ────────────────────────────
    compliance: 'الامتثال',
    tunisiaCompliance: 'امتثال تونس 2026',
    complianceScore: 'درجة الامتثال',
    compliant: 'متوافق',
    nonCompliant: 'غير متوافق',
    pendingReview: 'قيد المراجعة',
    runValidation: 'تحقق',
    loadReport: 'تحميل التقرير',
    refresh: 'تحديث',
    errors: 'أخطاء',
    warnings: 'تحذيرات',
    suggestions: 'اقتراحات',
    checksPassed: 'فحوصات ناجحة',
    sellerVatId: 'المعرف الجبائي للبائع',
    buyerVatId: 'المعرف الجبائي للمشتري',
    digitalSignature: 'التوقيع الرقمي',
    verify: 'تحقق',
    noSignature: 'لا يوجد توقيع',
    notVerified: 'لم يتم التحقق بعد',
    ttnSubmission: 'منصة الفاتورة الإلكترونية',
    submitToTTN: 'إرسال',
    submitted: 'تم الإرسال',
    submittedOn: 'تم الإرسال في',
    notSubmitted: 'لم يتم الإرسال بعد',
    mustBeCompliant: 'يجب أن تكون الفاتورة متوافقة أولاً',
    invoiceCompliant: 'الفاتورة متوافقة',
    invoiceNonCompliant: 'الفاتورة بها مشاكل امتثال',
    validationFailed: 'فشل التحقق',
    complianceLoadFailed: 'فشل تحميل تقرير الامتثال',
    signatureVerified: 'تم التحقق من التوقيع',
    noSignatureFound: 'لم يتم العثور على توقيع رقمي',
    ttnSubmitted: 'تم الإرسال إلى المنصة',
    xmlFormat: 'صيغة XML',
    goods: 'سلع',
    services: 'خدمات',
    mixed: 'مختلط',

    // ── Camera Capture ──────────────────────────────────────────
    scanInvoice: 'مسح الفاتورة',
    takePhoto: 'التقاط صورة',
    switchCamera: 'تبديل الكاميرا',
    cameraAccessDenied: 'تم رفض الوصول إلى الكاميرا. يرجى السماح بأذونات الكاميرا.',
    captureInvoice: 'ضع الفاتورة في الإطار واضغط على التقاط',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>('en');

  // Load saved language preference
  useEffect(() => {
    if (typeof window !== 'undefined') {
      const saved = localStorage.getItem('app-language') as Language;
      if (saved && ['en', 'fr', 'ar'].includes(saved)) {
        setLanguageState(saved);
      }
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    if (typeof window !== 'undefined') {
      localStorage.setItem('app-language', lang);
    }
    // Update document dir for RTL support
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = lang;
  };

  // Set initial dir
  useEffect(() => {
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  const dir = language === 'ar' ? 'rtl' : 'ltr';

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};
