"use client";

import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'fr' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  dir: 'ltr' | 'rtl';
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // ── Navigation & Layout ─────────────────────────────────────
    dashboard: 'Dashboard',
    aiExtraction: 'AI Extraction',
    invoiceManagement: 'Invoice Management',
    aiAdvisor: 'AI Advisor',
    settings: 'Settings',
    logout: 'Logout',
    auditTrail: 'Audit Trail',
    invoices: 'Invoices',
    navMain: 'Main',
    navAITools: 'AI Tools',
    navFinance: 'Finance',
    navSystem: 'System',

    // ── Dashboard ───────────────────────────────────────────────
    totalRevenue: 'Total Revenue',
    totalExpenses: 'Total Expenses',
    financialTrends: 'Financial Trends',
    totalAmount: 'Total Amount',
    totalInvoices: 'Total Invoices',
    needsReview: 'Needs Review',
    avgInvoiceValue: 'Avg Invoice Value',
    monthlyInvoiceTrend: 'Monthly Invoice Trend',
    topVendors: 'Top Vendors',
    invoiceStatusBreakdown: 'Invoice Status Breakdown',
    monthlyInvoiceVolume: 'Monthly Invoice Volume',
    recentInvoices: 'Recent Invoices',
    quickStats: 'Quick Stats',
    totalProcessed: 'Total Processed',
    reviewRate: 'Review Rate',
    topVendor: 'Top Vendor',
    noData: 'No data available',

    // ── AI Extraction ───────────────────────────────────────────
    uploadInvoice: 'Upload Invoice',
    dragDrop: 'Drag & drop your PDF or image here',
    extractedData: 'Extracted Data',
    saveInvoice: 'Save Invoice',
    multiFile: 'Multi-file',
    zipSupport: 'ZIP support',
    batchUpload: 'Batch Upload',
    processing: 'Processing',
    completed: 'Completed',
    failed: 'Failed',

    // ── Invoice Management ──────────────────────────────────────
    createInvoice: 'Create Invoice',
    allInvoices: 'All Invoices',
    invoiceNumber: 'Invoice Number',
    supplier: 'Supplier',
    amount: 'Amount',
    date: 'Date',
    status: 'Status',
    actions: 'Actions',
    exportPDF: 'Export PDF',
    exportExcel: 'Export Excel',
    exportAll: 'Export All',
    exportAllExcel: 'Export All (Excel)',
    description: 'Description',
    vat: 'VAT',

    // ── Search & Filters ────────────────────────────────────────
    searchInvoices: 'Search invoices by vendor, invoice number, notes...',
    filters: 'Filters',
    clearAll: 'Clear all',
    allStatuses: 'All statuses',
    allVendors: 'All vendors',
    allCurrencies: 'All currencies',
    sortBy: 'Sort by',
    dateAdded: 'Date added',
    invoiceDate: 'Invoice date',
    vendor: 'Vendor',
    dateFrom: 'Date from',
    dateTo: 'Date to',
    minAmount: 'Min amount',
    maxAmount: 'Max amount',
    currency: 'Currency',
    results: 'results',
    result: 'result',
    page: 'Page',
    of: 'of',
    total: 'Total',
    previous: 'Previous',
    next: 'Next',
    noInvoicesMatch: 'No invoices match your filters',
    tryAdjusting: 'Try adjusting your search or filters',
    clearAllFilters: 'Clear all filters',
    noInvoicesYet: 'No invoices yet. Upload a file in AI Extraction or create one manually.',
    invoice: 'invoice',

    // ── Create Invoice Dialog ───────────────────────────────────
    invoiceDetails: 'Invoice Details',
    invoiceNo: 'Invoice Number',
    invoiceDateLabel: 'Invoice Date',
    dueDate: 'Due Date',
    vendorFrom: 'Vendor (From)',
    vendorName: 'Vendor / Supplier Name',
    billTo: 'Bill To (Customer)',
    name: 'Name',
    email: 'Email',
    address: 'Address',
    lineItems: 'Line Items',
    addItem: 'Add Item',
    qty: 'Qty',
    unitPrice: 'Unit Price',
    totals: 'Totals',
    subtotal: 'Subtotal',
    tax: 'Tax',
    discount: 'Discount',
    grandTotal: 'Grand Total',
    paymentMethod: 'Payment Method',
    notes: 'Notes',
    cancel: 'Cancel',
    creating: 'Creating...',
    manageExport: 'Manage and export your invoices with AI-powered tools',

    // ── Logo & Signature ───────────────────────────────────────
    logoAndSignature: 'Logo & Signature',
    companyLogo: 'Company Logo',
    clickToUploadLogo: 'Click to upload logo',
    signature: 'Signature',
    clickToUploadSignature: 'Click to upload signature',
    authorizedSignature: 'Authorized Signature',

    // ── Share & QR Code ────────────────────────────────────────
    shareInvoice: 'Share Invoice',
    shareQrCode: 'Share / QR Code',
    shareCodeLabel: 'Share Code',
    shareCodeDesc: 'Anyone on the platform can use this code to view the invoice details',
    shareCodeCopied: 'Share code copied!',
    scanToVerify: 'Scan to verify',

    // ── Invoice Lookup ─────────────────────────────────────────
    lookupInvoice: 'Lookup Invoice',
    lookupDesc: 'Enter a share code to view invoice details',
    enterShareCode: 'Enter a share code',
    invoiceNotFound: 'Invoice not found',
    search: 'Search',

    // ── AI Advisor ──────────────────────────────────────────────
    askAI: 'Ask AI Advisor...',
    send: 'Send',
    newChat: 'New Chat',
    aiFinancialAdvisor: 'AI Financial Advisor',
    aiAdvisorDesc: 'Ask me anything about your invoices, spending patterns, vendor analysis, or financial insights.',
    realData: 'real data',
    tryAskingAbout: 'Try asking about',
    spendingTrends: 'Spending Trends',
    costOptimization: 'Cost Optimization',
    reviewNeeded: 'Review Needed',
    monthlySummary: 'Monthly Summary',
    financialHealth: 'Financial Health',
    realTimeAnalysis: 'Real-time analysis',
    multiTurnChat: 'Multi-turn chat',
    yourDataOnly: 'Your data only',
    analyzingData: 'Analyzing your data...',
    poweredByAI: 'Powered by AI — Analyzes your real invoice data',
    aiResponseNote: 'AI analyzes your real invoice data. Responses may take a moment.',
    spendingTrendsQ: 'What are my spending trends over the last few months? Are there any patterns I should know about?',
    topVendorsQ: 'Who are my top vendors by spending? How much do I spend with each?',
    costOptimizationQ: 'Based on my invoices, where can I optimize costs or reduce spending?',
    reviewNeededQ: 'Which invoices need human review? What issues were flagged?',
    monthlySummaryQ: 'Give me a complete summary of this month\'s invoices — totals, vendors, and any anomalies.',
    financialHealthQ: 'How is my overall financial health based on the invoice data? Any recommendations?',

    // ── Audit Trail ─────────────────────────────────────────────
    actionType: 'Action type',
    allActions: 'All actions',
    user: 'User',
    details: 'Details',
    ipAddress: 'IP Address',
    timestamp: 'Timestamp',
    login: 'Login',
    registration: 'Registration',
    invoiceUpload: 'Invoice Upload',
    invoiceUpdate: 'Invoice Update',
    export: 'Export',
    invoiceView: 'Invoice View',
    invoiceDelete: 'Invoice Delete',
    profileUpdate: 'Profile Update',
    aiAdvisorChat: 'AI Advisor Chat',

    // ── Auth ────────────────────────────────────────────────────
    admin: 'Admin',
    client: 'Client',
    month: 'Month',
    revenue: 'Revenue',
    expenses: 'Expenses',

    // ── Theme ───────────────────────────────────────────────────
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    systemTheme: 'System',
    language: 'Language',
    english: 'English',
    french: 'French',
    arabic: 'Arabic',

    // ── User Management ────────────────────────────────────────
    userManagement: 'User Management',
    userManagementDesc: 'Manage all users, roles and permissions',
    users: 'Users',
    addUser: 'Add User',
    editUser: 'Edit User',
    createUser: 'Create User',
    saveChanges: 'Save Changes',
    deleteUser: 'Delete User',
    deleteUserTitle: 'Delete User',
    deleteUserConfirm: 'Are you sure you want to permanently delete',
    deleteUserWarning: 'This action cannot be undone.',
    delete: 'Delete',
    activateUser: 'Activate User',
    deactivateUser: 'Deactivate User',
    active: 'Active',
    inactive: 'Inactive',
    role: 'Role',
    allRoles: 'All roles',
    password: 'Password',
    newPassword: 'New Password',
    leaveBlankPassword: 'Leave blank to keep current',
    searchUsers: 'Search Users',
    searchByNameEmail: 'Search by name or email...',
    noUsersFound: 'No users found',
    noUsersYet: 'No users have been created yet',
    createdAt: 'Created',
    lastLogin: 'Last Login',

    // ── Notifications ──────────────────────────────────────────
    notifications: 'Notifications',
    notificationCenter: 'Notification Center',
    notificationPreferences: 'Notification Preferences',
    markAllRead: 'Mark all as read',
    viewAll: 'View All',
    noNotifications: 'No notifications',
    noNotificationsYet: 'You have no notifications yet',
    allNotifications: 'All Notifications',
    unread: 'Unread',
    read: 'Read',
    allCategories: 'All categories',
    extraction: 'Extraction',
    invoiceActivity: 'Invoice Activity',
    system: 'System',
    broadcast: 'Broadcast',
    deleteNotification: 'Delete Notification',
    preferences: 'Preferences',
    channels: 'Channels',
    inApp: 'In-App',
    sms: 'SMS',
    notificationTypes: 'Notification Types',
    quietHours: 'Quiet Hours',
    quietHoursDesc: 'Pause non-urgent notifications during specified hours',
    startTime: 'Start Time',
    endTime: 'End Time',
    dailyDigest: 'Daily Digest',
    dailyDigestDesc: 'Receive a summary of notifications instead of individual alerts',
    digestFrequency: 'Frequency',
    digestTime: 'Delivery Time',
    daily: 'Daily',
    weekly: 'Weekly',
    saving: 'Saving...',
    saved: 'Saved',
    save: 'Save',

    // ── Organization / SaaS ────────────────────────────────────
    team: 'Team',
    teamManagement: 'Team Management',
    teamManagementDesc: 'Manage your organization members and invitations',
    inviteMember: 'Invite Member',
    sendInvitation: 'Send Invitation',
    invitationSent: 'Invitation sent to',
    pendingInvitations: 'Pending Invitations',
    revoke: 'Revoke',
    revokeInvitation: 'Revoke Invitation',
    revokeInvitationConfirm: 'Revoke the invitation sent to',
    removeMember: 'Remove Member',
    removeMemberConfirm: 'Are you sure you want to remove',
    remove: 'Remove',
    roleUpdated: 'Role updated',
    memberRemoved: 'Member removed',
    invitationRevoked: 'Invitation revoked',
    members: 'Members',
    owner: 'Owner',
    member: 'Member',
    you: 'you',
    orgSettings: 'Settings',
    orgSettingsDesc: 'Manage your organization settings',
    orgName: 'Organization Name',
    orgNamePlaceholder: 'e.g. Acme Corp',
    createOrganization: 'Create Organization',
    switchedToOrg: 'Switched organization',
    switchOrgFailed: 'Failed to switch organization',
    createOrgFailed: 'Failed to create organization',
    general: 'General',
    orgGeneralDesc: 'Basic organization settings',
    defaultCurrency: 'Default Currency',
    timezone: 'Timezone',
    branding: 'Branding',
    brandingDesc: 'Customize your organization appearance',
    primaryColor: 'Primary Color',
    billing: 'Billing',
    currentPlan: 'Current Plan',
    manageBilling: 'Manage Billing',
    invoicesThisMonth: 'Invoices this month',
    teamMembers: 'Team members',
    aiQueries: 'AI queries this month',
    storage: 'Storage (MB)',
    upgradeToPro: 'Upgrade to Pro',
    upgradeToEnterprise: 'Upgrade to Enterprise',
    billingUnavailable: 'Billing information unavailable',
    dangerZone: 'Danger Zone',
    deactivateOrg: 'Deactivate Organization',
    deleteOrgWarning: 'Deactivating the organization will remove access for all members.',
    deactivateOrgConfirm: 'This will deactivate the organization. This can be reversed by contacting support.',
    deactivate: 'Deactivate',

    // ── Tunisia 2026 E-Invoicing Compliance ────────────────────────────
    compliance: 'Compliance',
    tunisiaCompliance: 'Tunisia 2026 Compliance',
    complianceScore: 'Compliance Score',
    compliant: 'Compliant',
    nonCompliant: 'Non-compliant',
    pendingReview: 'Pending',
    runValidation: 'Validate',
    loadReport: 'Load Report',
    refresh: 'Refresh',
    errors: 'Errors',
    warnings: 'Warnings',
    suggestions: 'Suggestions',
    checksPassed: 'checks passed',
    sellerVatId: 'Seller VAT ID',
    buyerVatId: 'Buyer VAT ID',
    digitalSignature: 'Digital Signature',
    verify: 'Verify',
    noSignature: 'No signature',
    notVerified: 'Not verified yet',
    ttnSubmission: 'TTN El Fatoora',
    submitToTTN: 'Submit',
    submitted: 'Submitted',
    submittedOn: 'Submitted on',
    notSubmitted: 'Not submitted yet',
    mustBeCompliant: 'Invoice must be compliant first',
    invoiceCompliant: 'Invoice is compliant',
    invoiceNonCompliant: 'Invoice has compliance issues',
    validationFailed: 'Validation failed',
    complianceLoadFailed: 'Failed to load compliance report',
    signatureVerified: 'Signature verified',
    noSignatureFound: 'No digital signature found',
    ttnSubmitted: 'Submitted to TTN',
    xmlFormat: 'XML Format',
    goods: 'Goods',
    services: 'Services',
    mixed: 'Mixed',

    // ── Camera Capture ──────────────────────────────────────────
    scanInvoice: 'Scan Invoice',
    takePhoto: 'Take Photo',
    switchCamera: 'Switch Camera',
    cameraAccessDenied: 'Camera access denied. Please allow camera permissions.',
    captureInvoice: 'Position the invoice in frame and tap capture',

    // ── Language Selector ──────────────────────────────────────
    invoiceLanguage: 'Invoice Language',
    autoDetect: 'Auto Detect',

    // ── Scan & Import ─────────────────────────────────────────
    scanImport: 'Scan & Import',
    scanImportDesc: 'Scan a QR code from a printed invoice to import it into your dashboard',
    scanQrCode: 'Scan QR Code',
    scanningQr: 'Point camera at the QR code on the invoice',
    importInvoice: 'Import Invoice',
    importingInvoice: 'Importing invoice...',
    invoiceImported: 'Invoice imported successfully!',
    alreadyImported: 'This invoice has already been imported',
    ownInvoice: 'This invoice already belongs to your organization',
    invoicePreview: 'Invoice Preview',
    addToDashboard: 'Add to My Dashboard',
    orEnterCode: 'Or enter share code manually',
    scanAnother: 'Scan Another',

    // ── TEJ Withholding Tax ────────────────────────────────────
    withholdingTax: 'Withholding Tax',
    tejTitle: 'Withholding Tax Certificates',
    tejSubtitle: 'Generate TEJ-compliant retenue à la source declarations',
    tejDeclarationInfo: 'Declaration Information',
    tejDeclarationType: 'Declaration Type',
    tejYear: 'Year',
    tejMonth: 'Month',
    tejQuarter: 'Quarter',
    tejFilingDate: 'Filing Date',
    tejReference: 'Reference',
    tejReferencePlaceholder: 'Auto-generated if empty',
    tejDeclarant: 'Declarant (Withholding Agent)',
    tejTaxId: 'Tax ID (Matricule Fiscal)',
    tejCompanyName: 'Company Name',
    tejCompanyNamePlaceholder: 'e.g. Société Exemple SARL',
    tejStreet: 'Street',
    tejPostalCode: 'Postal Code',
    tejCity: 'City',
    tejGovernorate: 'Governorate',
    tejActivity: 'Business Activity',
    tejActivityPlaceholder: 'e.g. IT Services',
    tejBeneficiaries: 'Beneficiaries',
    tejBeneficiary: 'Beneficiary',
    tejAddBeneficiary: 'Add Beneficiary',
    tejBenId: 'Tax ID / Passport',
    tejBenType: 'Type',
    tejOperations: 'Operations',
    tejOperation: 'Operation',
    tejAddOperation: 'Add Operation',
    tejWithholdingType: 'Withholding Type',
    tejRateCategory: 'Rate Category',
    tejGrossAmount: 'Gross Amount',
    tejRate: 'Rate (%)',
    tejInvoiceRef: 'Invoice Ref',
    tejGenerate: 'Generate XML Certificate',
    tejGenerateSuccess: 'Certificate generated successfully',
    tejGenerateFailed: 'Certificate generation failed',
    tejValidation: 'Schema Validation',
    tejValid: 'Valid',
    tejInvalid: 'Invalid',
    tejMetadata: 'Metadata',
    tejSchemaVersion: 'Schema Version',
    tejGeneratedAt: 'Generated At',
    tejChecksum: 'Checksum',
    tejViewXml: 'View XML',
    tejHideXml: 'Hide XML',
    tejCopyXml: 'Copy XML',
    tejXmlCopied: 'XML copied to clipboard',
    tejDownloadXml: 'Download XML',
    tejExportPdf: 'Export PDF Certificate',
    tejPdfExported: 'PDF exported successfully',
    tejXmlPreview: 'XML Preview',
    tejRatesReference: 'Rates Reference',
    tejThreshold: 'Threshold',
    tejBatchCSV: 'Batch CSV',
    tejBatchUpload: 'Batch Upload from CSV',
    tejCSVDropHint: 'Upload a CSV file with beneficiary operations',
    tejSelectCSV: 'Select CSV File',
    tejCSVFormat: 'Required CSV columns:',
    tejGenerateBatch: 'Generate from CSV',
    tejBatchSuccess: 'Batch generation successful',
    tejRowsProcessed: 'rows processed',
    tejRowsSkipped: 'rows skipped',
    tejRow: 'Row',
    tejCreateTab: 'Create',
    tejCertificatesTab: 'Certificates',
    tejSearchCertificates: 'Search by reference, declarant...',
    tejDraft: 'Draft',
    tejApproved: 'Approved',
    tejRejected: 'Rejected',
    tejNoCertificates: 'No certificates yet. Create your first withholding certificate.',
    tejLoadFailed: 'Failed to load data',
    tejDeleteConfirm: 'Are you sure you want to delete this certificate?',
    tejDeleteSuccess: 'Certificate deleted',
    tejSubmitConfirm: 'Submit this certificate to TEJ? This cannot be undone.',
    tejSubmitSuccess: 'Certificate submitted to TEJ',
    tejSubmitToTEJ: 'Submit to TEJ',
    tejWithholding: 'Withholding',
    tejTotalGross: 'Total Gross',
    tejTotalWithholding: 'Total Withholding',
    tejTotalNet: 'Total Net',
    tejTotalCertificates: 'Total Certificates',
    tejStatusBreakdown: 'Status Breakdown',
    tejByType: 'By Operation Type',
    tejTimeline: 'Certificates Timeline',
    tejRecentCertificates: 'Recent Certificates',
    tejTEJReference: 'TEJ Reference',

    // ── Registration Wizard ────────────────────────────────────
    regStepOf: 'Step {step} of {total}',
    regCancel: 'Cancel',
    regPrevious: 'Previous',
    regNext: 'Next',
    regCreateAccount: 'Create Account',

    regStep1Title: 'Activity Type',
    regStep1Subtitle: 'Select your business activity type',
    regCommercial: 'Commercial',
    regCommercialDesc: 'Buying and selling of goods',
    regService: 'Service',
    regServiceDesc: 'Service-based activities',
    regIndustrial: 'Industrial',
    regIndustrialDesc: 'Manufacturing and production',
    regLiberalProfession: 'Liberal Profession',
    regLiberalProfessionDesc: 'Doctors, lawyers, consultants...',
    regArtisanal: 'Artisanal',
    regArtisanalDesc: 'Handicraft and artisan activities',

    regStep2Title: 'Person Type',
    regStep2Subtitle: 'Select your legal entity type',
    regPhysical: 'Natural Person',
    regPhysicalDesc: 'Individual / Sole proprietorship',
    regMoral: 'Legal Entity',
    regMoralDesc: 'Company / Organization',

    regStep3Title: 'Business Information',
    regStep3Subtitle: 'Tell us about your business',
    regCompanyName: 'Company / Business Name',
    regTaxId: 'Tax Identification Number',
    regPhone: 'Phone Number',
    regAddress: 'Address',

    regStep4Title: 'Account Details',
    regStep4Subtitle: 'Create your login credentials',

    regStep5Title: 'Confirmation',
    regStep5Subtitle: 'Review your information before creating your account',
    regActivityType: 'Activity Type',
    regPersonType: 'Person Type',
    regBusinessInfo: 'Business Information',
    regAccountInfo: 'Account Information',

    // ── Dashboard (new) ───────────────────────────────────────
    totalAmountDesc: 'Sum of all invoice grand totals',
    totalInvoicesDesc: 'Processed invoices in the system',
    needsReviewDesc: 'Flagged for human review',
    avgInvoiceValueDesc: 'Average grand total per invoice',
    monthlyInvoiceTrendDesc: 'Invoice amounts over time',
    noMonthlyData: 'No monthly data yet. Upload invoices to see trends.',
    byInvoiceAmount: 'By invoice amount',
    noVendorData: 'No vendor data yet',
    statusDistributionDesc: 'Distribution by processing status',
    noStatusData: 'No status data yet',
    latestProcessedInvoices: 'Latest processed invoices',
    monthlyVolumeDesc: 'Number of invoices processed per month',
    realTimeSummary: 'Real-time summary',
    invoicesInSystem: 'invoices in the system',
    invoicesFlaggedReview: 'invoices flagged for review',

    // ── AI Extraction (new) ───────────────────────────────────
    uploadingFile: 'Uploading File',
    ocrProcessing: 'OCR Processing',
    aiExtractionStep: 'AI Extraction',
    validationStep: 'Validation',
    supportedFormats: 'PDF, PNG, JPG, WEBP, TXT, XML, or ZIP',
    clickToBrowse: 'or click to browse - supports multiple files & ZIP',
    aiConfidence: 'AI Confidence',
    validInvoice: 'Valid Invoice',
    validationIssues: 'Validation Issues',
    needsHumanReview: 'This invoice needs human review. Some fields may be missing or inaccurate.',
    extractingData: 'Extracting invoice data...',
    mayTakeMoments: 'This may take a few moments',
    extractionFailed: 'Extraction Failed',
    reviewBeforeSaving: 'Review and edit the extracted information before saving',
    noLineItems: 'No line items extracted',
    changesLocalUntilSave: 'All changes are local until you save',
    inProgress: 'In progress...',
    batchComplete: 'Batch Processing Complete',
    processingFiles: 'Processing {n} file(s)...',
    batchResultMsg: 'Batch complete: {success}/{total} files processed',
    resultsInQueue: 'Results will appear in the batch queue',
    filesProcessed: '{n} of {total} files processed successfully.',
    batchFailed: 'Batch processing failed',
    processingTimeout: 'Processing timed out. Please try again.',
    processFileFailed: 'Failed to process file. Make sure the backend is running.',

    // ── Invoice Verification ─────────────────────────────────
    verifyInvoice: 'Verify Invoice',
    verifyScreen: '1. Verify',
    editScreen: '2. Edit & Save',
    verifyAndCorrect: 'Verify and correct the extracted invoice data',
    fieldsDetected: 'Detected',
    fieldsExtracted: 'Fields extracted',
    fields: 'fields',
    changes: 'changes',
    notDetected: 'Not detected',
    editFields: 'Edit & Correct Fields',
    backToInvoices: 'Back to Invoices',
    originalAI: 'Original (AI)',
    modified: 'Modified',
    keyboardShortcuts: 'Keyboard Shortcuts (?)',
    toggleShortcuts: 'Toggle shortcuts',

    // ── Audit Trail (new) ─────────────────────────────────────
    activityLog: 'Activity Log',
    noActivityYet: 'No activity recorded yet',
    actionsWillAppear: 'Actions will appear here as you use the system',
    justNow: 'Just now',
    minutesAgo: '{n}m ago',
    hoursAgo: '{n}h ago',
    daysAgo: '{n}d ago',
    monthsAgo: '{n}mo ago',
    event: 'event',
    events: 'events',
    method: 'Method',

    // ── Scan & Import (new) ───────────────────────────────────
    noQrFound: 'No QR code found in the image. Try again or enter the code manually.',
    invalidQrCode: 'QR code does not contain a valid invoice share code.',
    imageProcessFailed: 'Failed to process the image. Please try again.',
    lookupFailed: 'Failed to look up invoice',
    importFailed: 'Failed to import invoice',
    qrDetected: 'QR Code Detected',
    pointCameraAtQr: 'Point camera at QR code',
    analyzingImage: 'Analyzing Image...',
    detectingQr: 'Detecting QR code',
    tapToOpenScanner: 'Tap to Open Scanner',
    tapToTakePhoto: 'Tap to Take Photo',
    realtimeQrDesc: 'Real-time QR detection with auto-capture',
    takePhotoQrDesc: 'Take a photo of a QR code to scan',
    uploadFromGallery: 'Upload from gallery',
    lookingUpInvoice: 'Looking up invoice...',
    imported: 'Imported',
    preview: 'Preview',
    invoiceAddedToDashboard: 'Invoice added to your dashboard',
    unknownVendor: 'Unknown Vendor',
    close: 'Close',
    item: 'item',
    items: 'items',
    months: 'months',
    trackAllActivity: 'Track all actions and events across the platform',
    viewYourActivity: 'View your recent activity and actions',
    failedToLoadLogs: 'Failed to load activity logs',

    // ── Authentication (new) ─────────────────────────────────
    regSignIn: 'Sign In',
    regSignUp: 'Sign Up',
    regWelcomeBack: 'Welcome Back',
    regSignInDesc: 'Sign in to access your dashboard',
    regJoinSmartInvoice: 'Join SmartInvoice AI today',
    regEmail: 'Email Address',
    regPassword: 'Password',
    regConfirmPassword: 'Confirm Password',
    regFullName: 'Full Name',
    regForgotPassword: 'Forgot password?',
    regOrContinueWith: 'OR CONTINUE WITH',
    regContinueWithGoogle: 'Continue with Google',
    regPasswordsMismatch: 'Passwords do not match!',
    regPasswordTooShort: 'Password must be at least 6 characters.',
    regConnectionError: 'Unable to connect to server. Make sure the backend is running.',
    regResetPassword: 'Reset Password',
    regResetPasswordDesc: 'Enter your email to receive a reset code.',
    regEnterResetCode: 'Enter the 6-digit code sent to your email and choose a new password.',
    regResetCode: 'Reset Code',
    regNewPassword: 'New Password',
    regSendResetCode: 'Send Reset Code',
    regResetMyPassword: 'Reset My Password',
    regResetSuccess: 'Password reset successfully! You can now sign in.',
    regResetCodeSent: 'A reset code has been sent to your email.',
    regAgreeToTerms: 'I agree to the',
    regTermsOfService: 'Terms of Service',
    regAnd: 'and',
    regPrivacyPolicy: 'Privacy Policy',

    // ── Invoice Management Toast Messages ────────────────────
    failedToLoadInvoices: 'Failed to load invoices',
    failedToExport: 'Failed to export',
    allInvoicesExported: 'All invoices exported as Excel',
    enterVendorOrInvoice: 'Enter at least a vendor name or invoice number',
    invoiceCreated: 'Invoice created successfully!',
    failedToCreateInvoice: 'Failed to create invoice',
    imageTooLarge: 'Image must be less than 2MB',
    failedToLoadShare: 'Failed to load share info',
    failedToLoadInvoice: 'Failed to load invoice details',
    invoiceUpdated: 'Invoice updated successfully!',
    failedToUpdateInvoice: 'Failed to update invoice',
    failedToDeleteInvoice: 'Failed to delete invoice',
    failedToUpdateStatus: 'Failed to update status',
    failedToLoadHistory: 'Failed to load history',

    // ── Org Settings Toast Messages ──────────────────────────
    orgLoadFailed: 'Failed to load organization details',
    billingLoadFailed: 'Failed to load billing info',
    orgSaveFailed: 'Failed to save settings',
    checkoutFailed: 'Failed to start checkout',
    billingPortalFailed: 'Failed to open billing portal',
  },

  fr: {
    // ── Navigation & Layout ─────────────────────────────────────
    dashboard: 'Tableau de bord',
    aiExtraction: 'Extraction IA',
    invoiceManagement: 'Gestion des factures',
    aiAdvisor: 'Conseiller IA',
    settings: 'Paramètres',
    logout: 'Déconnexion',
    auditTrail: 'Journal d\'audit',
    invoices: 'Factures',
    navMain: 'Principal',
    navAITools: 'Outils IA',
    navFinance: 'Finance',
    navSystem: 'Système',

    // ── Dashboard ───────────────────────────────────────────────
    totalRevenue: 'Revenu total',
    totalExpenses: 'Dépenses totales',
    financialTrends: 'Tendances financières',
    totalAmount: 'Montant total',
    totalInvoices: 'Total factures',
    needsReview: 'À vérifier',
    avgInvoiceValue: 'Valeur moyenne',
    monthlyInvoiceTrend: 'Tendance mensuelle des factures',
    topVendors: 'Top fournisseurs',
    invoiceStatusBreakdown: 'Répartition par statut',
    monthlyInvoiceVolume: 'Volume mensuel des factures',
    recentInvoices: 'Factures récentes',
    quickStats: 'Statistiques rapides',
    totalProcessed: 'Total traité',
    reviewRate: 'Taux de vérification',
    topVendor: 'Fournisseur principal',
    noData: 'Aucune donnée disponible',

    // ── AI Extraction ───────────────────────────────────────────
    uploadInvoice: 'Télécharger la facture',
    dragDrop: 'Glissez-déposez votre PDF ou image ici',
    extractedData: 'Données extraites',
    saveInvoice: 'Enregistrer la facture',
    multiFile: 'Multi-fichier',
    zipSupport: 'Support ZIP',
    batchUpload: 'Téléchargement par lot',
    processing: 'En cours',
    completed: 'Terminé',
    failed: 'Échoué',

    // ── Invoice Management ──────────────────────────────────────
    createInvoice: 'Créer une facture',
    allInvoices: 'Toutes les factures',
    invoiceNumber: 'Numéro de facture',
    supplier: 'Fournisseur',
    amount: 'Montant',
    date: 'Date',
    status: 'Statut',
    actions: 'Actions',
    exportPDF: 'Exporter PDF',
    exportExcel: 'Exporter Excel',
    exportAll: 'Tout exporter',
    exportAllExcel: 'Tout exporter (Excel)',
    description: 'Description',
    vat: 'TVA',

    // ── Search & Filters ────────────────────────────────────────
    searchInvoices: 'Rechercher par fournisseur, numéro, notes...',
    filters: 'Filtres',
    clearAll: 'Tout effacer',
    allStatuses: 'Tous les statuts',
    allVendors: 'Tous les fournisseurs',
    allCurrencies: 'Toutes les devises',
    sortBy: 'Trier par',
    dateAdded: 'Date d\'ajout',
    invoiceDate: 'Date de facture',
    vendor: 'Fournisseur',
    dateFrom: 'Date début',
    dateTo: 'Date fin',
    minAmount: 'Montant min',
    maxAmount: 'Montant max',
    currency: 'Devise',
    results: 'résultats',
    result: 'résultat',
    page: 'Page',
    of: 'de',
    total: 'Total',
    previous: 'Précédent',
    next: 'Suivant',
    noInvoicesMatch: 'Aucune facture ne correspond à vos filtres',
    tryAdjusting: 'Essayez d\'ajuster votre recherche ou vos filtres',
    clearAllFilters: 'Effacer tous les filtres',
    noInvoicesYet: 'Pas encore de factures. Téléchargez un fichier ou créez-en une manuellement.',
    invoice: 'facture',

    // ── Create Invoice Dialog ───────────────────────────────────
    invoiceDetails: 'Détails de la facture',
    invoiceNo: 'Numéro de facture',
    invoiceDateLabel: 'Date de facture',
    dueDate: 'Date d\'échéance',
    vendorFrom: 'Fournisseur (De)',
    vendorName: 'Nom du fournisseur',
    billTo: 'Facturer à (Client)',
    name: 'Nom',
    email: 'E-mail',
    address: 'Adresse',
    lineItems: 'Articles',
    addItem: 'Ajouter un article',
    qty: 'Qté',
    unitPrice: 'Prix unitaire',
    totals: 'Totaux',
    subtotal: 'Sous-total',
    tax: 'Taxe',
    discount: 'Remise',
    grandTotal: 'Total général',
    paymentMethod: 'Mode de paiement',
    notes: 'Notes',
    cancel: 'Annuler',
    creating: 'Création...',
    manageExport: 'Gérez et exportez vos factures avec des outils alimentés par l\'IA',

    // ── Logo & Signature ───────────────────────────────────────
    logoAndSignature: 'Logo & Signature',
    companyLogo: 'Logo de l\'entreprise',
    clickToUploadLogo: 'Cliquez pour télécharger le logo',
    signature: 'Signature',
    clickToUploadSignature: 'Cliquez pour télécharger la signature',
    authorizedSignature: 'Signature autorisée',

    // ── Share & QR Code ────────────────────────────────────────
    shareInvoice: 'Partager la facture',
    shareQrCode: 'Partager / Code QR',
    shareCodeLabel: 'Code de partage',
    shareCodeDesc: 'Toute personne sur la plateforme peut utiliser ce code pour consulter les détails de la facture',
    shareCodeCopied: 'Code de partage copié !',
    scanToVerify: 'Scanner pour vérifier',

    // ── Invoice Lookup ─────────────────────────────────────────
    lookupInvoice: 'Rechercher une facture',
    lookupDesc: 'Entrez un code de partage pour voir les détails de la facture',
    enterShareCode: 'Entrez un code de partage',
    invoiceNotFound: 'Facture introuvable',
    search: 'Rechercher',

    // ── AI Advisor ──────────────────────────────────────────────
    askAI: 'Demander au conseiller IA...',
    send: 'Envoyer',
    newChat: 'Nouvelle discussion',
    aiFinancialAdvisor: 'Conseiller financier IA',
    aiAdvisorDesc: 'Posez-moi des questions sur vos factures, vos dépenses, vos fournisseurs ou vos analyses financières.',
    realData: 'données réelles',
    tryAskingAbout: 'Essayez de demander',
    spendingTrends: 'Tendances de dépenses',
    costOptimization: 'Optimisation des coûts',
    reviewNeeded: 'Vérification requise',
    monthlySummary: 'Résumé mensuel',
    financialHealth: 'Santé financière',
    realTimeAnalysis: 'Analyse en temps réel',
    multiTurnChat: 'Discussion continue',
    yourDataOnly: 'Vos données uniquement',
    analyzingData: 'Analyse de vos données...',
    poweredByAI: 'Propulsé par l\'IA — Analyse vos vraies données de factures',
    aiResponseNote: 'L\'IA analyse vos vraies données de factures. Les réponses peuvent prendre un moment.',
    spendingTrendsQ: 'Quelles sont mes tendances de dépenses ces derniers mois ? Y a-t-il des tendances que je devrais connaître ?',
    topVendorsQ: 'Quels sont mes principaux fournisseurs par dépenses ? Combien est-ce que je dépense avec chacun ?',
    costOptimizationQ: 'D\'après mes factures, où puis-je optimiser les coûts ou réduire les dépenses ?',
    reviewNeededQ: 'Quelles factures nécessitent une vérification humaine ? Quels problèmes ont été signalés ?',
    monthlySummaryQ: 'Donnez-moi un résumé complet des factures de ce mois — totaux, fournisseurs et anomalies.',
    financialHealthQ: 'Comment est ma santé financière globale d\'après les données de facturation ? Des recommandations ?',

    // ── Audit Trail ─────────────────────────────────────────────
    actionType: 'Type d\'action',
    allActions: 'Toutes les actions',
    user: 'Utilisateur',
    details: 'Détails',
    ipAddress: 'Adresse IP',
    timestamp: 'Horodatage',
    login: 'Connexion',
    registration: 'Inscription',
    invoiceUpload: 'Téléchargement de facture',
    invoiceUpdate: 'Mise à jour de facture',
    export: 'Exportation',
    invoiceView: 'Consultation de facture',
    invoiceDelete: 'Suppression de facture',
    profileUpdate: 'Mise à jour du profil',
    aiAdvisorChat: 'Discussion IA',

    // ── Auth ────────────────────────────────────────────────────
    admin: 'Admin',
    client: 'Client',
    month: 'Mois',
    revenue: 'Revenu',
    expenses: 'Dépenses',

    // ── Theme ───────────────────────────────────────────────────
    darkMode: 'Mode sombre',
    lightMode: 'Mode clair',
    systemTheme: 'Système',
    language: 'Langue',
    english: 'Anglais',
    french: 'Français',
    arabic: 'Arabe',

    // ── User Management ────────────────────────────────────────
    userManagement: 'Gestion des utilisateurs',
    userManagementDesc: 'Gérer tous les utilisateurs, rôles et permissions',
    users: 'Utilisateurs',
    addUser: 'Ajouter un utilisateur',
    editUser: 'Modifier l\'utilisateur',
    createUser: 'Créer l\'utilisateur',
    saveChanges: 'Enregistrer',
    deleteUser: 'Supprimer l\'utilisateur',
    deleteUserTitle: 'Supprimer l\'utilisateur',
    deleteUserConfirm: 'Êtes-vous sûr de vouloir supprimer définitivement',
    deleteUserWarning: 'Cette action est irréversible.',
    delete: 'Supprimer',
    activateUser: 'Activer l\'utilisateur',
    deactivateUser: 'Désactiver l\'utilisateur',
    active: 'Actif',
    inactive: 'Inactif',
    role: 'Rôle',
    allRoles: 'Tous les rôles',
    password: 'Mot de passe',
    newPassword: 'Nouveau mot de passe',
    leaveBlankPassword: 'Laisser vide pour conserver l\'actuel',
    searchUsers: 'Rechercher des utilisateurs',
    searchByNameEmail: 'Rechercher par nom ou email...',
    noUsersFound: 'Aucun utilisateur trouvé',
    noUsersYet: 'Aucun utilisateur n\'a encore été créé',
    createdAt: 'Créé le',
    lastLogin: 'Dernière connexion',

    // ── Notifications ──────────────────────────────────────────
    notifications: 'Notifications',
    notificationCenter: 'Centre de notifications',
    notificationPreferences: 'Préférences de notification',
    markAllRead: 'Tout marquer comme lu',
    viewAll: 'Voir tout',
    noNotifications: 'Aucune notification',
    noNotificationsYet: 'Vous n\'avez pas encore de notifications',
    allNotifications: 'Toutes les notifications',
    unread: 'Non lu',
    read: 'Lu',
    allCategories: 'Toutes les catégories',
    extraction: 'Extraction',
    invoiceActivity: 'Activité de facture',
    system: 'Système',
    broadcast: 'Diffusion',
    deleteNotification: 'Supprimer la notification',
    preferences: 'Préférences',
    channels: 'Canaux',
    inApp: 'Dans l\'app',
    sms: 'SMS',
    notificationTypes: 'Types de notification',
    quietHours: 'Heures calmes',
    quietHoursDesc: 'Suspendre les notifications non urgentes pendant les heures spécifiées',
    startTime: 'Heure de début',
    endTime: 'Heure de fin',
    dailyDigest: 'Résumé quotidien',
    dailyDigestDesc: 'Recevoir un résumé des notifications au lieu d\'alertes individuelles',
    digestFrequency: 'Fréquence',
    digestTime: 'Heure de livraison',
    daily: 'Quotidien',
    weekly: 'Hebdomadaire',
    saving: 'Enregistrement...',
    saved: 'Enregistré',
    save: 'Enregistrer',

    // ── Organization / SaaS ────────────────────────────────────
    team: 'Équipe',
    teamManagement: 'Gestion d\'équipe',
    teamManagementDesc: 'Gérer les membres et les invitations de votre organisation',
    inviteMember: 'Inviter un membre',
    sendInvitation: 'Envoyer l\'invitation',
    invitationSent: 'Invitation envoyée à',
    pendingInvitations: 'Invitations en attente',
    revoke: 'Révoquer',
    revokeInvitation: 'Révoquer l\'invitation',
    revokeInvitationConfirm: 'Révoquer l\'invitation envoyée à',
    removeMember: 'Retirer le membre',
    removeMemberConfirm: 'Êtes-vous sûr de vouloir retirer',
    remove: 'Retirer',
    roleUpdated: 'Rôle mis à jour',
    memberRemoved: 'Membre retiré',
    invitationRevoked: 'Invitation révoquée',
    members: 'Membres',
    owner: 'Propriétaire',
    member: 'Membre',
    you: 'vous',
    orgSettings: 'Paramètres',
    orgSettingsDesc: 'Gérer les paramètres de votre organisation',
    orgName: 'Nom de l\'organisation',
    orgNamePlaceholder: 'ex. Acme Corp',
    createOrganization: 'Créer une organisation',
    switchedToOrg: 'Organisation changée',
    switchOrgFailed: 'Échec du changement d\'organisation',
    createOrgFailed: 'Échec de la création de l\'organisation',
    general: 'Général',
    orgGeneralDesc: 'Paramètres de base de l\'organisation',
    defaultCurrency: 'Devise par défaut',
    timezone: 'Fuseau horaire',
    branding: 'Image de marque',
    brandingDesc: 'Personnaliser l\'apparence de votre organisation',
    primaryColor: 'Couleur principale',
    billing: 'Facturation',
    currentPlan: 'Plan actuel',
    manageBilling: 'Gérer la facturation',
    invoicesThisMonth: 'Factures ce mois-ci',
    teamMembers: 'Membres de l\'équipe',
    aiQueries: 'Requêtes IA ce mois-ci',
    storage: 'Stockage (Mo)',
    upgradeToPro: 'Passer au Pro',
    upgradeToEnterprise: 'Passer à l\'Enterprise',
    billingUnavailable: 'Informations de facturation indisponibles',
    dangerZone: 'Zone de danger',
    deactivateOrg: 'Désactiver l\'organisation',
    deleteOrgWarning: 'La désactivation supprimera l\'accès pour tous les membres.',
    deactivateOrgConfirm: 'Cela désactivera l\'organisation. Cela peut être annulé en contactant le support.',
    deactivate: 'Désactiver',

    // ── Tunisia 2026 E-Invoicing Compliance ────────────────────────────
    compliance: 'Conformité',
    tunisiaCompliance: 'Conformité Tunisie 2026',
    complianceScore: 'Score de conformité',
    compliant: 'Conforme',
    nonCompliant: 'Non conforme',
    pendingReview: 'En attente',
    runValidation: 'Valider',
    loadReport: 'Charger le rapport',
    refresh: 'Actualiser',
    errors: 'Erreurs',
    warnings: 'Avertissements',
    suggestions: 'Suggestions',
    checksPassed: 'vérifications réussies',
    sellerVatId: 'Matricule fiscale vendeur',
    buyerVatId: 'Matricule fiscale acheteur',
    digitalSignature: 'Signature numérique',
    verify: 'Vérifier',
    noSignature: 'Pas de signature',
    notVerified: 'Pas encore vérifié',
    ttnSubmission: 'TTN El Fatoora',
    submitToTTN: 'Soumettre',
    submitted: 'Soumis',
    submittedOn: 'Soumis le',
    notSubmitted: 'Pas encore soumis',
    mustBeCompliant: 'La facture doit être conforme',
    invoiceCompliant: 'La facture est conforme',
    invoiceNonCompliant: 'La facture a des problèmes de conformité',
    validationFailed: 'Échec de la validation',
    complianceLoadFailed: 'Échec du chargement du rapport',
    signatureVerified: 'Signature vérifiée',
    noSignatureFound: 'Aucune signature numérique trouvée',
    ttnSubmitted: 'Soumis au TTN',
    xmlFormat: 'Format XML',
    goods: 'Biens',
    services: 'Services',
    mixed: 'Mixte',

    // ── Camera Capture ──────────────────────────────────────────
    scanInvoice: 'Scanner la facture',
    takePhoto: 'Prendre une photo',
    switchCamera: 'Changer de caméra',
    cameraAccessDenied: "Accès à la caméra refusé. Veuillez autoriser l'accès.",
    captureInvoice: 'Positionnez la facture dans le cadre et appuyez sur capturer',

    // ── Language Selector ──────────────────────────────────────
    invoiceLanguage: 'Langue de la facture',
    autoDetect: 'Détection auto',

    // ── Scan & Import ─────────────────────────────────────────
    scanImport: 'Scanner & Importer',
    scanImportDesc: 'Scannez un code QR d\'une facture imprimée pour l\'importer dans votre tableau de bord',
    scanQrCode: 'Scanner le code QR',
    scanningQr: 'Dirigez la caméra vers le code QR de la facture',
    importInvoice: 'Importer la facture',
    importingInvoice: 'Importation en cours...',
    invoiceImported: 'Facture importée avec succès !',
    alreadyImported: 'Cette facture a déjà été importée',
    ownInvoice: 'Cette facture appartient déjà à votre organisation',
    invoicePreview: 'Aperçu de la facture',
    addToDashboard: 'Ajouter à mon tableau de bord',
    orEnterCode: 'Ou entrez le code manuellement',
    scanAnother: 'Scanner une autre',

    // ── TEJ Withholding Tax ────────────────────────────────────
    withholdingTax: 'Retenue à la Source',
    tejTitle: 'Certificats de Retenue à la Source',
    tejSubtitle: 'Générer des déclarations de retenue conformes au TEJ',
    tejDeclarationInfo: 'Informations de la Déclaration',
    tejDeclarationType: 'Type de Déclaration',
    tejYear: 'Année',
    tejMonth: 'Mois',
    tejQuarter: 'Trimestre',
    tejFilingDate: 'Date de Dépôt',
    tejReference: 'Référence',
    tejReferencePlaceholder: 'Auto-générée si vide',
    tejDeclarant: 'Déclarant (Agent de Retenue)',
    tejTaxId: 'Matricule Fiscal',
    tejCompanyName: 'Raison Sociale',
    tejCompanyNamePlaceholder: 'ex. Société Exemple SARL',
    tejStreet: 'Rue',
    tejPostalCode: 'Code Postal',
    tejCity: 'Ville',
    tejGovernorate: 'Gouvernorat',
    tejActivity: 'Activité',
    tejActivityPlaceholder: 'ex. Services informatiques',
    tejBeneficiaries: 'Bénéficiaires',
    tejBeneficiary: 'Bénéficiaire',
    tejAddBeneficiary: 'Ajouter un Bénéficiaire',
    tejBenId: 'Matricule Fiscal / Passeport',
    tejBenType: 'Type',
    tejOperations: 'Opérations',
    tejOperation: 'Opération',
    tejAddOperation: 'Ajouter une Opération',
    tejWithholdingType: 'Type de Retenue',
    tejRateCategory: 'Catégorie de Taux',
    tejGrossAmount: 'Montant Brut',
    tejRate: 'Taux (%)',
    tejInvoiceRef: 'Réf. Facture',
    tejGenerate: 'Générer le Certificat XML',
    tejGenerateSuccess: 'Certificat généré avec succès',
    tejGenerateFailed: 'Échec de la génération du certificat',
    tejValidation: 'Validation du Schéma',
    tejValid: 'Valide',
    tejInvalid: 'Invalide',
    tejMetadata: 'Métadonnées',
    tejSchemaVersion: 'Version du Schéma',
    tejGeneratedAt: 'Généré le',
    tejChecksum: 'Somme de contrôle',
    tejViewXml: 'Voir le XML',
    tejHideXml: 'Masquer le XML',
    tejCopyXml: 'Copier le XML',
    tejXmlCopied: 'XML copié dans le presse-papiers',
    tejDownloadXml: 'Télécharger le XML',
    tejExportPdf: 'Exporter le Certificat PDF',
    tejPdfExported: 'PDF exporté avec succès',
    tejXmlPreview: 'Aperçu XML',
    tejRatesReference: 'Référence des Taux',
    tejThreshold: 'Seuil',
    tejBatchCSV: 'CSV par Lot',
    tejBatchUpload: 'Import par Lot depuis CSV',
    tejCSVDropHint: 'Téléchargez un fichier CSV avec les opérations des bénéficiaires',
    tejSelectCSV: 'Sélectionner un Fichier CSV',
    tejCSVFormat: 'Colonnes CSV requises :',
    tejGenerateBatch: 'Générer depuis CSV',
    tejBatchSuccess: 'Génération par lot réussie',
    tejRowsProcessed: 'lignes traitées',
    tejRowsSkipped: 'lignes ignorées',
    tejRow: 'Ligne',
    tejCreateTab: 'Créer',
    tejCertificatesTab: 'Certificats',
    tejSearchCertificates: 'Rechercher par référence, déclarant...',
    tejDraft: 'Brouillon',
    tejApproved: 'Approuvé',
    tejRejected: 'Rejeté',
    tejNoCertificates: 'Aucun certificat. Créez votre premier certificat de retenue.',
    tejLoadFailed: 'Échec du chargement des données',
    tejDeleteConfirm: 'Voulez-vous vraiment supprimer ce certificat ?',
    tejDeleteSuccess: 'Certificat supprimé',
    tejSubmitConfirm: 'Soumettre ce certificat au TEJ ? Cette action est irréversible.',
    tejSubmitSuccess: 'Certificat soumis au TEJ',
    tejSubmitToTEJ: 'Soumettre au TEJ',
    tejWithholding: 'Retenue',
    tejTotalGross: 'Total Brut',
    tejTotalWithholding: 'Total Retenue',
    tejTotalNet: 'Total Net',
    tejTotalCertificates: 'Total Certificats',
    tejStatusBreakdown: 'Répartition par Statut',
    tejByType: 'Par Type d\'Opération',
    tejTimeline: 'Chronologie des Certificats',
    tejRecentCertificates: 'Certificats Récents',
    tejTEJReference: 'Référence TEJ',

    // ── Registration Wizard ────────────────────────────────────
    regStepOf: 'Étape {step} sur {total}',
    regCancel: 'Annuler',
    regPrevious: 'Précédent',
    regNext: 'Suivant',
    regCreateAccount: 'Créer le compte',

    regStep1Title: 'Type d\'activité',
    regStep1Subtitle: 'Sélectionnez votre type d\'activité',
    regCommercial: 'Commerciale',
    regCommercialDesc: 'Achat et vente de marchandises',
    regService: 'Service',
    regServiceDesc: 'Activités de services',
    regIndustrial: 'Industrielle',
    regIndustrialDesc: 'Fabrication et production',
    regLiberalProfession: 'Profession Libérale',
    regLiberalProfessionDesc: 'Médecins, avocats, consultants...',
    regArtisanal: 'Artisanale',
    regArtisanalDesc: 'Activités artisanales',

    regStep2Title: 'Type de personne',
    regStep2Subtitle: 'Sélectionnez votre type d\'entité juridique',
    regPhysical: 'Personne Physique',
    regPhysicalDesc: 'Individu / Entreprise individuelle',
    regMoral: 'Personne Morale',
    regMoralDesc: 'Société / Organisation',

    regStep3Title: 'Informations commerciales',
    regStep3Subtitle: 'Parlez-nous de votre entreprise',
    regCompanyName: 'Nom de la société / entreprise',
    regTaxId: 'Matricule fiscal',
    regPhone: 'Numéro de téléphone',
    regAddress: 'Adresse',

    regStep4Title: 'Détails du compte',
    regStep4Subtitle: 'Créez vos identifiants de connexion',

    regStep5Title: 'Confirmation',
    regStep5Subtitle: 'Vérifiez vos informations avant de créer votre compte',
    regActivityType: 'Type d\'activité',
    regPersonType: 'Type de personne',
    regBusinessInfo: 'Informations commerciales',
    regAccountInfo: 'Informations du compte',

    // ── Dashboard (new) ───────────────────────────────────────
    totalAmountDesc: 'Somme de tous les totaux des factures',
    totalInvoicesDesc: 'Factures traitées dans le système',
    needsReviewDesc: 'Signalées pour vérification humaine',
    avgInvoiceValueDesc: 'Total moyen par facture',
    monthlyInvoiceTrendDesc: 'Montants des factures au fil du temps',
    noMonthlyData: 'Pas encore de données mensuelles. Importez des factures pour voir les tendances.',
    byInvoiceAmount: 'Par montant de facture',
    noVendorData: 'Pas encore de données fournisseur',
    statusDistributionDesc: 'Répartition par statut de traitement',
    noStatusData: 'Pas encore de données de statut',
    latestProcessedInvoices: 'Dernières factures traitées',
    monthlyVolumeDesc: 'Nombre de factures traitées par mois',
    realTimeSummary: 'Résumé en temps réel',
    invoicesInSystem: 'factures dans le système',
    invoicesFlaggedReview: 'factures signalées pour vérification',

    // ── AI Extraction (new) ───────────────────────────────────
    uploadingFile: 'Téléchargement du fichier',
    ocrProcessing: 'Traitement OCR',
    aiExtractionStep: 'Extraction IA',
    validationStep: 'Validation',
    supportedFormats: 'PDF, PNG, JPG, WEBP, TXT, XML ou ZIP',
    clickToBrowse: 'ou cliquez pour parcourir - supporte plusieurs fichiers & ZIP',
    aiConfidence: 'Confiance IA',
    validInvoice: 'Facture valide',
    validationIssues: 'Problèmes de validation',
    needsHumanReview: 'Cette facture nécessite une vérification humaine. Certains champs peuvent être manquants ou inexacts.',
    extractingData: 'Extraction des données de facture...',
    mayTakeMoments: 'Cela peut prendre quelques instants',
    extractionFailed: 'Échec de l\'extraction',
    reviewBeforeSaving: 'Vérifiez et modifiez les informations extraites avant d\'enregistrer',
    noLineItems: 'Aucun élément de ligne extrait',
    changesLocalUntilSave: 'Toutes les modifications sont locales jusqu\'à l\'enregistrement',
    inProgress: 'En cours...',
    batchComplete: 'Traitement par lot terminé',
    processingFiles: 'Traitement de {n} fichier(s)...',
    batchResultMsg: 'Lot terminé : {success}/{total} fichiers traités',
    resultsInQueue: 'Les résultats apparaîtront dans la file d\'attente',
    filesProcessed: '{n} sur {total} fichiers traités avec succès.',
    batchFailed: 'Échec du traitement par lot',
    processingTimeout: 'Le traitement a expiré. Veuillez réessayer.',
    processFileFailed: 'Échec du traitement du fichier. Vérifiez que le backend fonctionne.',

    // ── Invoice Verification ─────────────────────────────────
    verifyInvoice: 'Vérifier la facture',
    verifyScreen: '1. Vérifier',
    editScreen: '2. Modifier & Sauvegarder',
    verifyAndCorrect: 'Vérifiez et corrigez les données extraites de la facture',
    fieldsDetected: 'Détectés',
    fieldsExtracted: 'Champs extraits',
    fields: 'champs',
    changes: 'modifications',
    notDetected: 'Non détecté',
    editFields: 'Modifier & Corriger les champs',
    backToInvoices: 'Retour aux factures',
    originalAI: 'Original (IA)',
    modified: 'Modifié',
    keyboardShortcuts: 'Raccourcis clavier (?)',
    toggleShortcuts: 'Basculer les raccourcis',

    // ── Audit Trail (new) ─────────────────────────────────────
    activityLog: 'Journal d\'activité',
    noActivityYet: 'Aucune activité enregistrée',
    actionsWillAppear: 'Les actions apparaîtront ici au fur et à mesure de votre utilisation',
    justNow: 'À l\'instant',
    minutesAgo: 'il y a {n}min',
    hoursAgo: 'il y a {n}h',
    daysAgo: 'il y a {n}j',
    monthsAgo: 'il y a {n} mois',
    event: 'événement',
    events: 'événements',
    method: 'Méthode',

    // ── Scan & Import (new) ───────────────────────────────────
    noQrFound: 'Aucun code QR trouvé dans l\'image. Réessayez ou entrez le code manuellement.',
    invalidQrCode: 'Le code QR ne contient pas un code de partage de facture valide.',
    imageProcessFailed: 'Échec du traitement de l\'image. Veuillez réessayer.',
    lookupFailed: 'Échec de la recherche de facture',
    importFailed: 'Échec de l\'importation de la facture',
    qrDetected: 'Code QR détecté',
    pointCameraAtQr: 'Pointez la caméra vers le code QR',
    analyzingImage: 'Analyse de l\'image...',
    detectingQr: 'Détection du code QR',
    tapToOpenScanner: 'Appuyez pour ouvrir le scanner',
    tapToTakePhoto: 'Appuyez pour prendre une photo',
    realtimeQrDesc: 'Détection QR en temps réel avec capture automatique',
    takePhotoQrDesc: 'Prenez une photo d\'un code QR pour scanner',
    uploadFromGallery: 'Importer depuis la galerie',
    lookingUpInvoice: 'Recherche de la facture...',
    imported: 'Importé',
    preview: 'Aperçu',
    invoiceAddedToDashboard: 'Facture ajoutée à votre tableau de bord',
    unknownVendor: 'Fournisseur inconnu',
    close: 'Fermer',
    item: 'élément',
    items: 'éléments',
    months: 'mois',
    trackAllActivity: 'Suivre toutes les actions et événements sur la plateforme',
    viewYourActivity: 'Voir votre activité et vos actions récentes',
    failedToLoadLogs: 'Échec du chargement des journaux d\'activité',

    // ── Authentication (new) ─────────────────────────────────
    regSignIn: 'Se connecter',
    regSignUp: 'S\'inscrire',
    regWelcomeBack: 'Bon retour',
    regSignInDesc: 'Connectez-vous pour accéder à votre tableau de bord',
    regJoinSmartInvoice: 'Rejoignez SmartInvoice AI aujourd\'hui',
    regEmail: 'Adresse e-mail',
    regPassword: 'Mot de passe',
    regConfirmPassword: 'Confirmer le mot de passe',
    regFullName: 'Nom complet',
    regForgotPassword: 'Mot de passe oublié ?',
    regOrContinueWith: 'OU CONTINUER AVEC',
    regContinueWithGoogle: 'Continuer avec Google',
    regPasswordsMismatch: 'Les mots de passe ne correspondent pas !',
    regPasswordTooShort: 'Le mot de passe doit comporter au moins 6 caractères.',
    regConnectionError: 'Impossible de se connecter au serveur. Assurez-vous que le backend est en cours d\'exécution.',
    regResetPassword: 'Réinitialiser le mot de passe',
    regResetPasswordDesc: 'Entrez votre e-mail pour recevoir un code de réinitialisation.',
    regEnterResetCode: 'Entrez le code à 6 chiffres envoyé à votre e-mail et choisissez un nouveau mot de passe.',
    regResetCode: 'Code de réinitialisation',
    regNewPassword: 'Nouveau mot de passe',
    regSendResetCode: 'Envoyer le code',
    regResetMyPassword: 'Réinitialiser mon mot de passe',
    regResetSuccess: 'Mot de passe réinitialisé avec succès ! Vous pouvez maintenant vous connecter.',
    regResetCodeSent: 'Un code de réinitialisation a été envoyé à votre e-mail.',
    regAgreeToTerms: 'J\'accepte les',
    regTermsOfService: 'Conditions d\'utilisation',
    regAnd: 'et',
    regPrivacyPolicy: 'Politique de confidentialité',

    // ── Invoice Management Toast Messages ────────────────────
    failedToLoadInvoices: 'Échec du chargement des factures',
    failedToExport: 'Échec de l\'exportation',
    allInvoicesExported: 'Toutes les factures exportées en Excel',
    enterVendorOrInvoice: 'Entrez au moins un nom de fournisseur ou un numéro de facture',
    invoiceCreated: 'Facture créée avec succès !',
    failedToCreateInvoice: 'Échec de la création de la facture',
    imageTooLarge: 'L\'image doit être inférieure à 2 Mo',
    failedToLoadShare: 'Échec du chargement des informations de partage',
    failedToLoadInvoice: 'Échec du chargement des détails de la facture',
    invoiceUpdated: 'Facture mise à jour avec succès !',
    failedToUpdateInvoice: 'Échec de la mise à jour de la facture',
    failedToDeleteInvoice: 'Échec de la suppression de la facture',
    failedToUpdateStatus: 'Échec de la mise à jour du statut',
    failedToLoadHistory: 'Échec du chargement de l\'historique',

    // ── Org Settings Toast Messages ──────────────────────────
    orgLoadFailed: 'Échec du chargement des détails de l\'organisation',
    billingLoadFailed: 'Échec du chargement des informations de facturation',
    orgSaveFailed: 'Échec de l\'enregistrement des paramètres',
    checkoutFailed: 'Échec du démarrage du paiement',
    billingPortalFailed: 'Échec de l\'ouverture du portail de facturation',
  },

  ar: {
    // ── Navigation & Layout ─────────────────────────────────────
    dashboard: 'لوحة التحكم',
    aiExtraction: 'استخراج بالذكاء الاصطناعي',
    invoiceManagement: 'إدارة الفواتير',
    aiAdvisor: 'مستشار الذكاء الاصطناعي',
    settings: 'الإعدادات',
    logout: 'تسجيل الخروج',
    auditTrail: 'سجل التدقيق',
    invoices: 'الفواتير',
    navMain: 'الرئيسية',
    navAITools: 'أدوات الذكاء الاصطناعي',
    navFinance: 'المالية',
    navSystem: 'النظام',

    // ── Dashboard ───────────────────────────────────────────────
    totalRevenue: 'إجمالي الإيرادات',
    totalExpenses: 'إجمالي المصروفات',
    financialTrends: 'الاتجاهات المالية',
    totalAmount: 'المبلغ الإجمالي',
    totalInvoices: 'إجمالي الفواتير',
    needsReview: 'تحتاج مراجعة',
    avgInvoiceValue: 'متوسط قيمة الفاتورة',
    monthlyInvoiceTrend: 'اتجاه الفواتير الشهرية',
    topVendors: 'أهم الموردين',
    invoiceStatusBreakdown: 'توزيع حالات الفواتير',
    monthlyInvoiceVolume: 'حجم الفواتير الشهرية',
    recentInvoices: 'الفواتير الأخيرة',
    quickStats: 'إحصائيات سريعة',
    totalProcessed: 'إجمالي المعالج',
    reviewRate: 'معدل المراجعة',
    topVendor: 'المورد الرئيسي',
    noData: 'لا توجد بيانات',

    // ── AI Extraction ───────────────────────────────────────────
    uploadInvoice: 'تحميل فاتورة',
    dragDrop: 'اسحب وأفلت ملف PDF أو صورة هنا',
    extractedData: 'البيانات المستخرجة',
    saveInvoice: 'حفظ الفاتورة',
    multiFile: 'ملفات متعددة',
    zipSupport: 'دعم ZIP',
    batchUpload: 'تحميل دفعة',
    processing: 'قيد المعالجة',
    completed: 'مكتمل',
    failed: 'فشل',

    // ── Invoice Management ──────────────────────────────────────
    createInvoice: 'إنشاء فاتورة',
    allInvoices: 'جميع الفواتير',
    invoiceNumber: 'رقم الفاتورة',
    supplier: 'المورد',
    amount: 'المبلغ',
    date: 'التاريخ',
    status: 'الحالة',
    actions: 'الإجراءات',
    exportPDF: 'تصدير PDF',
    exportExcel: 'تصدير Excel',
    exportAll: 'تصدير الكل',
    exportAllExcel: 'تصدير الكل (Excel)',
    description: 'الوصف',
    vat: 'ضريبة القيمة المضافة',

    // ── Search & Filters ────────────────────────────────────────
    searchInvoices: 'البحث عن الفواتير بالمورد أو الرقم أو الملاحظات...',
    filters: 'الفلاتر',
    clearAll: 'مسح الكل',
    allStatuses: 'جميع الحالات',
    allVendors: 'جميع الموردين',
    allCurrencies: 'جميع العملات',
    sortBy: 'ترتيب حسب',
    dateAdded: 'تاريخ الإضافة',
    invoiceDate: 'تاريخ الفاتورة',
    vendor: 'المورد',
    dateFrom: 'من تاريخ',
    dateTo: 'إلى تاريخ',
    minAmount: 'الحد الأدنى',
    maxAmount: 'الحد الأقصى',
    currency: 'العملة',
    results: 'نتائج',
    result: 'نتيجة',
    page: 'صفحة',
    of: 'من',
    total: 'المجموع',
    previous: 'السابق',
    next: 'التالي',
    noInvoicesMatch: 'لا توجد فواتير تطابق الفلاتر',
    tryAdjusting: 'حاول تعديل البحث أو الفلاتر',
    clearAllFilters: 'مسح جميع الفلاتر',
    noInvoicesYet: 'لا توجد فواتير بعد. قم بتحميل ملف أو إنشاء فاتورة يدوياً.',
    invoice: 'فاتورة',

    // ── Create Invoice Dialog ───────────────────────────────────
    invoiceDetails: 'تفاصيل الفاتورة',
    invoiceNo: 'رقم الفاتورة',
    invoiceDateLabel: 'تاريخ الفاتورة',
    dueDate: 'تاريخ الاستحقاق',
    vendorFrom: 'المورد (من)',
    vendorName: 'اسم المورد',
    billTo: 'الفاتورة إلى (العميل)',
    name: 'الاسم',
    email: 'البريد الإلكتروني',
    address: 'العنوان',
    lineItems: 'البنود',
    addItem: 'إضافة بند',
    qty: 'الكمية',
    unitPrice: 'سعر الوحدة',
    totals: 'المجاميع',
    subtotal: 'المجموع الفرعي',
    tax: 'الضريبة',
    discount: 'الخصم',
    grandTotal: 'المجموع الكلي',
    paymentMethod: 'طريقة الدفع',
    notes: 'ملاحظات',
    cancel: 'إلغاء',
    creating: 'جاري الإنشاء...',
    manageExport: 'إدارة وتصدير الفواتير باستخدام أدوات الذكاء الاصطناعي',

    // ── Logo & Signature ───────────────────────────────────────
    logoAndSignature: 'الشعار والتوقيع',
    companyLogo: 'شعار الشركة',
    clickToUploadLogo: 'انقر لتحميل الشعار',
    signature: 'التوقيع',
    clickToUploadSignature: 'انقر لتحميل التوقيع',
    authorizedSignature: 'التوقيع المعتمد',

    // ── Share & QR Code ────────────────────────────────────────
    shareInvoice: 'مشاركة الفاتورة',
    shareQrCode: 'مشاركة / رمز QR',
    shareCodeLabel: 'رمز المشاركة',
    shareCodeDesc: 'يمكن لأي شخص على المنصة استخدام هذا الرمز لعرض تفاصيل الفاتورة',
    shareCodeCopied: 'تم نسخ رمز المشاركة!',
    scanToVerify: 'امسح للتحقق',

    // ── Invoice Lookup ─────────────────────────────────────────
    lookupInvoice: 'البحث عن فاتورة',
    lookupDesc: 'أدخل رمز المشاركة لعرض تفاصيل الفاتورة',
    enterShareCode: 'أدخل رمز المشاركة',
    invoiceNotFound: 'الفاتورة غير موجودة',
    search: 'بحث',

    // ── AI Advisor ──────────────────────────────────────────────
    askAI: 'اسأل مستشار الذكاء الاصطناعي...',
    send: 'إرسال',
    newChat: 'محادثة جديدة',
    aiFinancialAdvisor: 'مستشار مالي بالذكاء الاصطناعي',
    aiAdvisorDesc: 'اسألني عن فواتيرك وأنماط الإنفاق وتحليل الموردين أو الرؤى المالية.',
    realData: 'بيانات حقيقية',
    tryAskingAbout: 'جرب أن تسأل عن',
    spendingTrends: 'اتجاهات الإنفاق',
    costOptimization: 'تحسين التكاليف',
    reviewNeeded: 'تحتاج مراجعة',
    monthlySummary: 'ملخص شهري',
    financialHealth: 'الصحة المالية',
    realTimeAnalysis: 'تحليل فوري',
    multiTurnChat: 'محادثة متعددة',
    yourDataOnly: 'بياناتك فقط',
    analyzingData: 'جاري تحليل بياناتك...',
    poweredByAI: 'مدعوم بالذكاء الاصطناعي — يحلل بيانات فواتيرك الحقيقية',
    aiResponseNote: 'يحلل الذكاء الاصطناعي بيانات فواتيرك الحقيقية. قد تستغرق الردود بعض الوقت.',
    spendingTrendsQ: 'ما هي اتجاهات الإنفاق خلال الأشهر الأخيرة؟ هل هناك أنماط يجب أن أعرفها؟',
    topVendorsQ: 'من هم أهم الموردين حسب الإنفاق؟ كم أنفق مع كل واحد؟',
    costOptimizationQ: 'بناءً على فواتيري، أين يمكنني تحسين التكاليف أو تقليل الإنفاق؟',
    reviewNeededQ: 'ما هي الفواتير التي تحتاج مراجعة بشرية؟ ما هي المشاكل التي تم الإبلاغ عنها؟',
    monthlySummaryQ: 'أعطني ملخصاً كاملاً لفواتير هذا الشهر — الإجماليات والموردين وأي شذوذ.',
    financialHealthQ: 'كيف هي صحتي المالية العامة بناءً على بيانات الفواتير؟ هل من توصيات؟',

    // ── Audit Trail ─────────────────────────────────────────────
    actionType: 'نوع الإجراء',
    allActions: 'جميع الإجراءات',
    user: 'المستخدم',
    details: 'التفاصيل',
    ipAddress: 'عنوان IP',
    timestamp: 'الطابع الزمني',
    login: 'تسجيل الدخول',
    registration: 'التسجيل',
    invoiceUpload: 'تحميل فاتورة',
    invoiceUpdate: 'تحديث فاتورة',
    export: 'تصدير',
    invoiceView: 'عرض فاتورة',
    invoiceDelete: 'حذف فاتورة',
    profileUpdate: 'تحديث الملف الشخصي',
    aiAdvisorChat: 'محادثة المستشار',

    // ── Auth ────────────────────────────────────────────────────
    admin: 'مسؤول',
    client: 'عميل',
    month: 'الشهر',
    revenue: 'الإيرادات',
    expenses: 'المصروفات',

    // ── Theme ───────────────────────────────────────────────────
    darkMode: 'الوضع الداكن',
    lightMode: 'الوضع الفاتح',
    systemTheme: 'النظام',
    language: 'اللغة',
    english: 'الإنجليزية',
    french: 'الفرنسية',
    arabic: 'العربية',

    // ── User Management ────────────────────────────────────────
    userManagement: 'إدارة المستخدمين',
    userManagementDesc: 'إدارة جميع المستخدمين والأدوار والصلاحيات',
    users: 'المستخدمون',
    addUser: 'إضافة مستخدم',
    editUser: 'تعديل المستخدم',
    createUser: 'إنشاء المستخدم',
    saveChanges: 'حفظ التغييرات',
    deleteUser: 'حذف المستخدم',
    deleteUserTitle: 'حذف المستخدم',
    deleteUserConfirm: 'هل أنت متأكد من حذف',
    deleteUserWarning: 'لا يمكن التراجع عن هذا الإجراء.',
    delete: 'حذف',
    activateUser: 'تفعيل المستخدم',
    deactivateUser: 'تعطيل المستخدم',
    active: 'نشط',
    inactive: 'غير نشط',
    role: 'الدور',
    allRoles: 'جميع الأدوار',
    password: 'كلمة المرور',
    newPassword: 'كلمة مرور جديدة',
    leaveBlankPassword: 'اتركه فارغاً للإبقاء على الحالي',
    searchUsers: 'البحث عن المستخدمين',
    searchByNameEmail: 'البحث بالاسم أو البريد الإلكتروني...',
    noUsersFound: 'لم يتم العثور على مستخدمين',
    noUsersYet: 'لم يتم إنشاء أي مستخدمين بعد',
    createdAt: 'تاريخ الإنشاء',
    lastLogin: 'آخر تسجيل دخول',

    // ── Notifications ──────────────────────────────────────────
    notifications: 'الإشعارات',
    notificationCenter: 'مركز الإشعارات',
    notificationPreferences: 'تفضيلات الإشعارات',
    markAllRead: 'تحديد الكل كمقروء',
    viewAll: 'عرض الكل',
    noNotifications: 'لا توجد إشعارات',
    noNotificationsYet: 'ليس لديك إشعارات بعد',
    allNotifications: 'جميع الإشعارات',
    unread: 'غير مقروء',
    read: 'مقروء',
    allCategories: 'جميع الفئات',
    extraction: 'الاستخراج',
    invoiceActivity: 'نشاط الفاتورة',
    system: 'النظام',
    broadcast: 'بث عام',
    deleteNotification: 'حذف الإشعار',
    preferences: 'التفضيلات',
    channels: 'القنوات',
    inApp: 'داخل التطبيق',
    sms: 'رسالة نصية',
    notificationTypes: 'أنواع الإشعارات',
    quietHours: 'ساعات الهدوء',
    quietHoursDesc: 'إيقاف الإشعارات غير العاجلة خلال الساعات المحددة',
    startTime: 'وقت البدء',
    endTime: 'وقت الانتهاء',
    dailyDigest: 'ملخص يومي',
    dailyDigestDesc: 'استلام ملخص للإشعارات بدلاً من التنبيهات الفردية',
    digestFrequency: 'التكرار',
    digestTime: 'وقت التسليم',
    daily: 'يومي',
    weekly: 'أسبوعي',
    saving: 'جاري الحفظ...',
    saved: 'تم الحفظ',
    save: 'حفظ',

    // ── Organization / SaaS ────────────────────────────────────
    team: 'الفريق',
    teamManagement: 'إدارة الفريق',
    teamManagementDesc: 'إدارة أعضاء المنظمة والدعوات',
    inviteMember: 'دعوة عضو',
    sendInvitation: 'إرسال الدعوة',
    invitationSent: 'تم إرسال الدعوة إلى',
    pendingInvitations: 'الدعوات المعلقة',
    revoke: 'إلغاء',
    revokeInvitation: 'إلغاء الدعوة',
    revokeInvitationConfirm: 'إلغاء الدعوة المرسلة إلى',
    removeMember: 'إزالة العضو',
    removeMemberConfirm: 'هل أنت متأكد من إزالة',
    remove: 'إزالة',
    roleUpdated: 'تم تحديث الدور',
    memberRemoved: 'تم إزالة العضو',
    invitationRevoked: 'تم إلغاء الدعوة',
    members: 'الأعضاء',
    owner: 'المالك',
    member: 'عضو',
    you: 'أنت',
    orgSettings: 'الإعدادات',
    orgSettingsDesc: 'إدارة إعدادات المنظمة',
    orgName: 'اسم المنظمة',
    orgNamePlaceholder: 'مثال: شركة أكمي',
    createOrganization: 'إنشاء منظمة',
    switchedToOrg: 'تم تغيير المنظمة',
    switchOrgFailed: 'فشل تغيير المنظمة',
    createOrgFailed: 'فشل إنشاء المنظمة',
    general: 'عام',
    orgGeneralDesc: 'الإعدادات الأساسية للمنظمة',
    defaultCurrency: 'العملة الافتراضية',
    timezone: 'المنطقة الزمنية',
    branding: 'العلامة التجارية',
    brandingDesc: 'تخصيص مظهر المنظمة',
    primaryColor: 'اللون الرئيسي',
    billing: 'الفوترة',
    currentPlan: 'الخطة الحالية',
    manageBilling: 'إدارة الفوترة',
    invoicesThisMonth: 'الفواتير هذا الشهر',
    teamMembers: 'أعضاء الفريق',
    aiQueries: 'استعلامات الذكاء الاصطناعي هذا الشهر',
    storage: 'التخزين (ميجابايت)',
    upgradeToPro: 'الترقية إلى Pro',
    upgradeToEnterprise: 'الترقية إلى Enterprise',
    billingUnavailable: 'معلومات الفوترة غير متوفرة',
    dangerZone: 'منطقة الخطر',
    deactivateOrg: 'تعطيل المنظمة',
    deleteOrgWarning: 'سيؤدي التعطيل إلى إزالة الوصول لجميع الأعضاء.',
    deactivateOrgConfirm: 'سيؤدي هذا إلى تعطيل المنظمة. يمكن التراجع عن ذلك بالتواصل مع الدعم.',
    deactivate: 'تعطيل',

    // ── Tunisia 2026 E-Invoicing Compliance ────────────────────────────
    compliance: 'الامتثال',
    tunisiaCompliance: 'امتثال تونس 2026',
    complianceScore: 'درجة الامتثال',
    compliant: 'متوافق',
    nonCompliant: 'غير متوافق',
    pendingReview: 'قيد المراجعة',
    runValidation: 'تحقق',
    loadReport: 'تحميل التقرير',
    refresh: 'تحديث',
    errors: 'أخطاء',
    warnings: 'تحذيرات',
    suggestions: 'اقتراحات',
    checksPassed: 'فحوصات ناجحة',
    sellerVatId: 'المعرف الجبائي للبائع',
    buyerVatId: 'المعرف الجبائي للمشتري',
    digitalSignature: 'التوقيع الرقمي',
    verify: 'تحقق',
    noSignature: 'لا يوجد توقيع',
    notVerified: 'لم يتم التحقق بعد',
    ttnSubmission: 'منصة الفاتورة الإلكترونية',
    submitToTTN: 'إرسال',
    submitted: 'تم الإرسال',
    submittedOn: 'تم الإرسال في',
    notSubmitted: 'لم يتم الإرسال بعد',
    mustBeCompliant: 'يجب أن تكون الفاتورة متوافقة أولاً',
    invoiceCompliant: 'الفاتورة متوافقة',
    invoiceNonCompliant: 'الفاتورة بها مشاكل امتثال',
    validationFailed: 'فشل التحقق',
    complianceLoadFailed: 'فشل تحميل تقرير الامتثال',
    signatureVerified: 'تم التحقق من التوقيع',
    noSignatureFound: 'لم يتم العثور على توقيع رقمي',
    ttnSubmitted: 'تم الإرسال إلى المنصة',
    xmlFormat: 'صيغة XML',
    goods: 'سلع',
    services: 'خدمات',
    mixed: 'مختلط',

    // ── Camera Capture ──────────────────────────────────────────
    scanInvoice: 'مسح الفاتورة',
    takePhoto: 'التقاط صورة',
    switchCamera: 'تبديل الكاميرا',
    cameraAccessDenied: 'تم رفض الوصول إلى الكاميرا. يرجى السماح بأذونات الكاميرا.',
    captureInvoice: 'ضع الفاتورة في الإطار واضغط على التقاط',

    // ── Language Selector ──────────────────────────────────────
    invoiceLanguage: 'لغة الفاتورة',
    autoDetect: 'كشف تلقائي',

    // ── Scan & Import ─────────────────────────────────────────
    scanImport: 'مسح واستيراد',
    scanImportDesc: 'امسح رمز QR من فاتورة مطبوعة لاستيرادها إلى لوحة التحكم الخاصة بك',
    scanQrCode: 'مسح رمز QR',
    scanningQr: 'وجّه الكاميرا نحو رمز QR الموجود على الفاتورة',
    importInvoice: 'استيراد الفاتورة',
    importingInvoice: 'جاري استيراد الفاتورة...',
    invoiceImported: 'تم استيراد الفاتورة بنجاح!',
    alreadyImported: 'تم استيراد هذه الفاتورة بالفعل',
    ownInvoice: 'هذه الفاتورة تنتمي بالفعل إلى مؤسستك',
    invoicePreview: 'معاينة الفاتورة',
    addToDashboard: 'إضافة إلى لوحة التحكم',
    orEnterCode: 'أو أدخل الرمز يدوياً',
    scanAnother: 'مسح فاتورة أخرى',

    // ── TEJ Withholding Tax ────────────────────────────────────
    withholdingTax: 'الخصم من المنبع',
    tejTitle: 'شهادات الخصم من المنبع',
    tejSubtitle: 'إنشاء تصريحات الخصم المطابقة لنظام التصريح الإلكتروني الجبائي',
    tejDeclarationInfo: 'معلومات التصريح',
    tejDeclarationType: 'نوع التصريح',
    tejYear: 'السنة',
    tejMonth: 'الشهر',
    tejQuarter: 'الثلاثي',
    tejFilingDate: 'تاريخ الإيداع',
    tejReference: 'المرجع',
    tejReferencePlaceholder: 'يتم إنشاؤه تلقائياً إذا فارغ',
    tejDeclarant: 'المصرّح (وكيل الخصم)',
    tejTaxId: 'المعرّف الجبائي',
    tejCompanyName: 'الاسم الاجتماعي',
    tejCompanyNamePlaceholder: 'مثال: شركة المثال ش.م.م',
    tejStreet: 'الشارع',
    tejPostalCode: 'الرمز البريدي',
    tejCity: 'المدينة',
    tejGovernorate: 'الولاية',
    tejActivity: 'النشاط',
    tejActivityPlaceholder: 'مثال: خدمات المعلوماتية',
    tejBeneficiaries: 'المستفيدون',
    tejBeneficiary: 'المستفيد',
    tejAddBeneficiary: 'إضافة مستفيد',
    tejBenId: 'المعرّف الجبائي / جواز السفر',
    tejBenType: 'النوع',
    tejOperations: 'العمليات',
    tejOperation: 'العملية',
    tejAddOperation: 'إضافة عملية',
    tejWithholdingType: 'نوع الخصم',
    tejRateCategory: 'فئة النسبة',
    tejGrossAmount: 'المبلغ الإجمالي',
    tejRate: 'النسبة (%)',
    tejInvoiceRef: 'مرجع الفاتورة',
    tejGenerate: 'إنشاء شهادة XML',
    tejGenerateSuccess: 'تم إنشاء الشهادة بنجاح',
    tejGenerateFailed: 'فشل إنشاء الشهادة',
    tejValidation: 'التحقق من المخطط',
    tejValid: 'صالح',
    tejInvalid: 'غير صالح',
    tejMetadata: 'البيانات الوصفية',
    tejSchemaVersion: 'إصدار المخطط',
    tejGeneratedAt: 'تاريخ الإنشاء',
    tejChecksum: 'المجموع الاختباري',
    tejViewXml: 'عرض XML',
    tejHideXml: 'إخفاء XML',
    tejCopyXml: 'نسخ XML',
    tejXmlCopied: 'تم نسخ XML إلى الحافظة',
    tejDownloadXml: 'تحميل XML',
    tejExportPdf: 'تصدير شهادة PDF',
    tejPdfExported: 'تم تصدير PDF بنجاح',
    tejXmlPreview: 'معاينة XML',
    tejRatesReference: 'مرجع النسب',
    tejThreshold: 'الحد الأدنى',
    tejBatchCSV: 'دفعة CSV',
    tejBatchUpload: 'استيراد دفعة من CSV',
    tejCSVDropHint: 'قم بتحميل ملف CSV يحتوي على عمليات المستفيدين',
    tejSelectCSV: 'اختيار ملف CSV',
    tejCSVFormat: 'أعمدة CSV المطلوبة:',
    tejGenerateBatch: 'إنشاء من CSV',
    tejBatchSuccess: 'نجاح الإنشاء بالدفعة',
    tejRowsProcessed: 'صفوف معالجة',
    tejRowsSkipped: 'صفوف مُتجاوزة',
    tejRow: 'صف',
    tejCreateTab: 'إنشاء',
    tejCertificatesTab: 'الشهادات',
    tejSearchCertificates: 'البحث بالمرجع أو المصرّح...',
    tejDraft: 'مسودة',
    tejApproved: 'معتمد',
    tejRejected: 'مرفوض',
    tejNoCertificates: 'لا توجد شهادات بعد. أنشئ أول شهادة خصم.',
    tejLoadFailed: 'فشل تحميل البيانات',
    tejDeleteConfirm: 'هل أنت متأكد من حذف هذه الشهادة؟',
    tejDeleteSuccess: 'تم حذف الشهادة',
    tejSubmitConfirm: 'إرسال هذه الشهادة إلى النظام الجبائي؟ لا يمكن التراجع.',
    tejSubmitSuccess: 'تم إرسال الشهادة',
    tejSubmitToTEJ: 'إرسال إلى النظام الجبائي',
    tejWithholding: 'الخصم',
    tejTotalGross: 'إجمالي المبلغ الخام',
    tejTotalWithholding: 'إجمالي الخصم',
    tejTotalNet: 'إجمالي الصافي',
    tejTotalCertificates: 'إجمالي الشهادات',
    tejStatusBreakdown: 'توزيع الحالات',
    tejByType: 'حسب نوع العملية',
    tejTimeline: 'الجدول الزمني للشهادات',
    tejRecentCertificates: 'الشهادات الأخيرة',
    tejTEJReference: 'مرجع النظام الجبائي',

    // ── Registration Wizard ────────────────────────────────────
    regStepOf: 'الخطوة {step} من {total}',
    regCancel: 'إلغاء',
    regPrevious: 'السابق',
    regNext: 'التالي',
    regCreateAccount: 'إنشاء الحساب',

    regStep1Title: 'نوع النشاط',
    regStep1Subtitle: 'اختر نوع نشاطك التجاري',
    regCommercial: 'تجاري',
    regCommercialDesc: 'شراء وبيع البضائع',
    regService: 'خدمات',
    regServiceDesc: 'أنشطة خدمية',
    regIndustrial: 'صناعي',
    regIndustrialDesc: 'تصنيع وإنتاج',
    regLiberalProfession: 'مهنة حرة',
    regLiberalProfessionDesc: 'أطباء، محامون، مستشارون...',
    regArtisanal: 'حرفي',
    regArtisanalDesc: 'أنشطة حرفية',

    regStep2Title: 'نوع الشخص',
    regStep2Subtitle: 'اختر نوع الكيان القانوني',
    regPhysical: 'شخص طبيعي',
    regPhysicalDesc: 'فرد / مؤسسة فردية',
    regMoral: 'شخص معنوي',
    regMoralDesc: 'شركة / منظمة',

    regStep3Title: 'معلومات العمل',
    regStep3Subtitle: 'أخبرنا عن عملك',
    regCompanyName: 'اسم الشركة / المؤسسة',
    regTaxId: 'المعرّف الجبائي',
    regPhone: 'رقم الهاتف',
    regAddress: 'العنوان',

    regStep4Title: 'تفاصيل الحساب',
    regStep4Subtitle: 'أنشئ بيانات تسجيل الدخول',

    regStep5Title: 'التأكيد',
    regStep5Subtitle: 'راجع معلوماتك قبل إنشاء حسابك',
    regActivityType: 'نوع النشاط',
    regPersonType: 'نوع الشخص',
    regBusinessInfo: 'معلومات العمل',
    regAccountInfo: 'معلومات الحساب',

    // ── Dashboard (new) ───────────────────────────────────────
    totalAmountDesc: 'مجموع إجماليات جميع الفواتير',
    totalInvoicesDesc: 'الفواتير المعالجة في النظام',
    needsReviewDesc: 'مُعلَّمة للمراجعة البشرية',
    avgInvoiceValueDesc: 'متوسط الإجمالي لكل فاتورة',
    monthlyInvoiceTrendDesc: 'مبالغ الفواتير عبر الوقت',
    noMonthlyData: 'لا توجد بيانات شهرية بعد. قم بتحميل الفواتير لعرض الاتجاهات.',
    byInvoiceAmount: 'حسب مبلغ الفاتورة',
    noVendorData: 'لا توجد بيانات مورد بعد',
    statusDistributionDesc: 'التوزيع حسب حالة المعالجة',
    noStatusData: 'لا توجد بيانات حالة بعد',
    latestProcessedInvoices: 'آخر الفواتير المعالجة',
    monthlyVolumeDesc: 'عدد الفواتير المعالجة شهرياً',
    realTimeSummary: 'ملخص فوري',
    invoicesInSystem: 'فواتير في النظام',
    invoicesFlaggedReview: 'فواتير مُعلَّمة للمراجعة',

    // ── AI Extraction (new) ───────────────────────────────────
    uploadingFile: 'تحميل الملف',
    ocrProcessing: 'معالجة OCR',
    aiExtractionStep: 'استخراج بالذكاء الاصطناعي',
    validationStep: 'التحقق',
    supportedFormats: 'PDF, PNG, JPG, WEBP, TXT, XML أو ZIP',
    clickToBrowse: 'أو انقر للتصفح - يدعم ملفات متعددة و ZIP',
    aiConfidence: 'ثقة الذكاء الاصطناعي',
    validInvoice: 'فاتورة صالحة',
    validationIssues: 'مشاكل في التحقق',
    needsHumanReview: 'تحتاج هذه الفاتورة إلى مراجعة بشرية. قد تكون بعض الحقول مفقودة أو غير دقيقة.',
    extractingData: 'جاري استخراج بيانات الفاتورة...',
    mayTakeMoments: 'قد يستغرق هذا بضع لحظات',
    extractionFailed: 'فشل الاستخراج',
    reviewBeforeSaving: 'راجع وعدّل المعلومات المستخرجة قبل الحفظ',
    noLineItems: 'لم يتم استخراج أي عناصر',
    changesLocalUntilSave: 'جميع التغييرات محلية حتى تقوم بالحفظ',
    inProgress: 'قيد التنفيذ...',
    batchComplete: 'اكتمل المعالجة بالدفعة',
    processingFiles: 'معالجة {n} ملف(ات)...',
    batchResultMsg: 'اكتملت الدفعة: {success}/{total} ملفات معالجة',
    resultsInQueue: 'ستظهر النتائج في قائمة الانتظار',
    filesProcessed: '{n} من {total} ملفات تمت معالجتها بنجاح.',
    batchFailed: 'فشل المعالجة بالدفعة',
    processingTimeout: 'انتهت مهلة المعالجة. يرجى المحاولة مرة أخرى.',
    processFileFailed: 'فشل في معالجة الملف. تأكد من أن الخادم يعمل.',

    // ── Invoice Verification ─────────────────────────────────
    verifyInvoice: 'التحقق من الفاتورة',
    verifyScreen: '1. التحقق',
    editScreen: '2. تعديل وحفظ',
    verifyAndCorrect: 'تحقق وصحح البيانات المستخرجة من الفاتورة',
    fieldsDetected: 'مكتشفة',
    fieldsExtracted: 'الحقول المستخرجة',
    fields: 'حقول',
    changes: 'تغييرات',
    notDetected: 'غير مكتشف',
    editFields: 'تعديل وتصحيح الحقول',
    backToInvoices: 'العودة إلى الفواتير',
    originalAI: 'الأصلي (ذكاء اصطناعي)',
    modified: 'معدّل',
    keyboardShortcuts: 'اختصارات لوحة المفاتيح (?)',
    toggleShortcuts: 'تبديل الاختصارات',

    // ── Audit Trail (new) ─────────────────────────────────────
    activityLog: 'سجل النشاط',
    noActivityYet: 'لم يتم تسجيل أي نشاط بعد',
    actionsWillAppear: 'ستظهر الإجراءات هنا أثناء استخدامك للنظام',
    justNow: 'الآن',
    minutesAgo: 'منذ {n} دقيقة',
    hoursAgo: 'منذ {n} ساعة',
    daysAgo: 'منذ {n} يوم',
    monthsAgo: 'منذ {n} شهر',
    event: 'حدث',
    events: 'أحداث',
    method: 'الطريقة',

    // ── Scan & Import (new) ───────────────────────────────────
    noQrFound: 'لم يتم العثور على رمز QR في الصورة. حاول مرة أخرى أو أدخل الرمز يدوياً.',
    invalidQrCode: 'رمز QR لا يحتوي على رمز مشاركة فاتورة صالح.',
    imageProcessFailed: 'فشل في معالجة الصورة. يرجى المحاولة مرة أخرى.',
    lookupFailed: 'فشل في البحث عن الفاتورة',
    importFailed: 'فشل في استيراد الفاتورة',
    qrDetected: 'تم اكتشاف رمز QR',
    pointCameraAtQr: 'وجّه الكاميرا نحو رمز QR',
    analyzingImage: 'تحليل الصورة...',
    detectingQr: 'اكتشاف رمز QR',
    tapToOpenScanner: 'اضغط لفتح الماسح',
    tapToTakePhoto: 'اضغط لالتقاط صورة',
    realtimeQrDesc: 'اكتشاف QR في الوقت الفعلي مع التقاط تلقائي',
    takePhotoQrDesc: 'التقط صورة لرمز QR للمسح',
    uploadFromGallery: 'تحميل من المعرض',
    lookingUpInvoice: 'جاري البحث عن الفاتورة...',
    imported: 'تم الاستيراد',
    preview: 'معاينة',
    invoiceAddedToDashboard: 'تمت إضافة الفاتورة إلى لوحة التحكم',
    unknownVendor: 'مورد غير معروف',
    close: 'إغلاق',
    item: 'عنصر',
    items: 'عناصر',
    months: 'أشهر',
    trackAllActivity: 'تتبع جميع الإجراءات والأحداث عبر المنصة',
    viewYourActivity: 'عرض نشاطك وإجراءاتك الأخيرة',
    failedToLoadLogs: 'فشل في تحميل سجلات النشاط',

    // ── Authentication (new) ─────────────────────────────────
    regSignIn: 'تسجيل الدخول',
    regSignUp: 'إنشاء حساب',
    regWelcomeBack: 'مرحباً بعودتك',
    regSignInDesc: 'سجّل الدخول للوصول إلى لوحة التحكم',
    regJoinSmartInvoice: 'انضم إلى SmartInvoice AI اليوم',
    regEmail: 'البريد الإلكتروني',
    regPassword: 'كلمة المرور',
    regConfirmPassword: 'تأكيد كلمة المرور',
    regFullName: 'الاسم الكامل',
    regForgotPassword: 'نسيت كلمة المرور؟',
    regOrContinueWith: 'أو تابع باستخدام',
    regContinueWithGoogle: 'المتابعة مع جوجل',
    regPasswordsMismatch: 'كلمات المرور غير متطابقة!',
    regPasswordTooShort: 'يجب أن تتكون كلمة المرور من 6 أحرف على الأقل.',
    regConnectionError: 'تعذر الاتصال بالخادم. تأكد من تشغيل الخادم الخلفي.',
    regResetPassword: 'إعادة تعيين كلمة المرور',
    regResetPasswordDesc: 'أدخل بريدك الإلكتروني لتلقي رمز إعادة التعيين.',
    regEnterResetCode: 'أدخل الرمز المكون من 6 أرقام المرسل إلى بريدك الإلكتروني واختر كلمة مرور جديدة.',
    regResetCode: 'رمز إعادة التعيين',
    regNewPassword: 'كلمة المرور الجديدة',
    regSendResetCode: 'إرسال رمز إعادة التعيين',
    regResetMyPassword: 'إعادة تعيين كلمة المرور',
    regResetSuccess: 'تمت إعادة تعيين كلمة المرور بنجاح! يمكنك الآن تسجيل الدخول.',
    regResetCodeSent: 'تم إرسال رمز إعادة التعيين إلى بريدك الإلكتروني.',
    regAgreeToTerms: 'أوافق على',
    regTermsOfService: 'شروط الخدمة',
    regAnd: 'و',
    regPrivacyPolicy: 'سياسة الخصوصية',

    // ── Invoice Management Toast Messages ────────────────────
    failedToLoadInvoices: 'فشل في تحميل الفواتير',
    failedToExport: 'فشل في التصدير',
    allInvoicesExported: 'تم تصدير جميع الفواتير بصيغة Excel',
    enterVendorOrInvoice: 'أدخل اسم المورد أو رقم الفاتورة على الأقل',
    invoiceCreated: 'تم إنشاء الفاتورة بنجاح!',
    failedToCreateInvoice: 'فشل في إنشاء الفاتورة',
    imageTooLarge: 'يجب أن تكون الصورة أقل من 2 ميجابايت',
    failedToLoadShare: 'فشل في تحميل معلومات المشاركة',
    failedToLoadInvoice: 'فشل في تحميل تفاصيل الفاتورة',
    invoiceUpdated: 'تم تحديث الفاتورة بنجاح!',
    failedToUpdateInvoice: 'فشل في تحديث الفاتورة',
    failedToDeleteInvoice: 'فشل في حذف الفاتورة',
    failedToUpdateStatus: 'فشل في تحديث الحالة',
    failedToLoadHistory: 'فشل في تحميل السجل',

    // ── Org Settings Toast Messages ──────────────────────────
    orgLoadFailed: 'فشل في تحميل تفاصيل المنظمة',
    billingLoadFailed: 'فشل في تحميل معلومات الفوترة',
    orgSaveFailed: 'فشل في حفظ الإعدادات',
    checkoutFailed: 'فشل في بدء الدفع',
    billingPortalFailed: 'فشل في فتح بوابة الفوترة',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>('en');

  // Load saved language preference
  useEffect(() => {
    if (typeof window !== 'undefined') {
      const saved = localStorage.getItem('app-language') as Language;
      if (saved && ['en', 'fr', 'ar'].includes(saved)) {
        setLanguageState(saved);
      }
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    if (typeof window !== 'undefined') {
      localStorage.setItem('app-language', lang);
    }
  };

  // Sync dir/lang attributes on the client only (after hydration)
  useEffect(() => {
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  const dir = language === 'ar' ? 'rtl' : 'ltr';

  const t = (key: string): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};
